//! Parse/compile-only validation, aligned with `agenterm_rh::check` (see
//! `crates/agenterm-rh/src/check.rs`) — same "ok means it type-checks
//! syntactically, without running it" contract, different mechanism.
//!
//! rh validates a Rhai `AST` against its own subset rules without a runtime.
//! qjs has no equivalent subset layer (yet); "check" here means QuickJS
//! itself parses and *declares* the source as an ES module without
//! evaluating it — `Module::declare` compiles/resolves module-level
//! `import`/`export` structure and catches syntax errors, but does not run
//! top-level statements (verified in tests below: a script that would set a
//! global as a side effect leaves it unset after `check`).
//!
//! Known gap vs. rh (tracked, not silently assumed away): rh's
//! `check_with_project_validation` additionally walks a project-relative
//! `import` graph and validates every shipped-API reference
//! (`crates/agenterm-rh/src/project_import.rs`, `api_validate.rs`). qjs has
//! no analogous project-import/API-catalog validation yet — see PRD
//! "qjs execution backend" risk list. `check()` here is intentionally
//! narrower until that lands.

use rquickjs::{CatchResultExt, Context, Module, Runtime};

use crate::error::QjsError;

/// Parse/compile `source` as an ES module without executing it. `label` is
/// used only for QuickJS's own error messages (filename in a stack trace),
/// not for any path resolution — callers own path safety themselves (see
/// `check_many`, which resolves/validates paths before calling this).
pub fn check(source: &str, label: &str) -> Result<(), QjsError> {
    let runtime = Runtime::new().map_err(|err| QjsError::Check(err.to_string()))?;
    let context = Context::full(&runtime).map_err(|err| QjsError::Check(err.to_string()))?;
    context.with(
        |ctx| match Module::declare(ctx.clone(), label, source).catch(&ctx) {
            Ok(_module) => Ok(()),
            // .catch() turns the generic "Exception generated by QuickJS" into
            // the actual thrown SyntaxError's message (line/column, what token
            // was unexpected) — without it every syntax error looks identical
            // and useless for a human or CI log to act on.
            Err(err) => Err(QjsError::Parse(err.to_string())),
        },
    )
}

#[cfg(test)]
mod tests {
    use super::check;

    #[test]
    fn accepts_valid_module_source() {
        check("export default 40 + 2;", "ok.js").expect("valid module source");
    }

    #[test]
    fn rejects_syntax_errors() {
        let error = check("this is not valid js (((", "bad.js").expect_err("syntax error");
        assert!(matches!(error, super::QjsError::Parse(_)));
    }

    #[test]
    fn does_not_execute_top_level_side_effects() {
        // If check() ran the module body, this would leave a trace we could
        // detect; since each check() call is its own fresh Runtime/Context,
        // the only way to observe "did it run" is within one call — proven
        // directly against rquickjs in the QJS-M1 spike (module_declare_probe,
        // since removed) and re-asserted here at the check() API boundary via
        // a script that would throw if executed but not if merely parsed.
        check(
            "if (true) { throw new Error('should not run'); }",
            "throws.js",
        )
        .expect("declare-only check must not execute the throwing statement");
    }
}
