//! Parse/compile-only validation, aligned with `agenterm_rh::check` (see
//! `crates/agenterm-rh/src/check.rs`) — same "ok means it type-checks
//! syntactically, without running it" contract, different mechanism.
//!
//! rh validates a Rhai `AST` against its own subset rules without a runtime.
//! qjs has no equivalent subset layer (yet); "check" here means QuickJS
//! itself parses and *declares* the source as an ES module without
//! evaluating it — `Module::declare` compiles/resolves module-level
//! `import`/`export` structure and catches syntax errors, but does not run
//! top-level statements (verified in tests below: a script that would set a
//! global as a side effect leaves it unset after `check`).
//!
//! Known gap vs. rh, re-verified and corrected 2026-08-08 (the previous
//! version of this note, written before QJS-M5, lumped two separate
//! things together — worth being precise about which half is actually
//! done, not just re-stating "known gap" indefinitely):
//!
//! - **Closed** (QJS-M5c): rh's `check_with_project_validation` walks a
//!   project-relative `import` graph
//!   (`crates/agenterm-rh/src/project_import.rs`) — qjs's
//!   [`check_with_project_validation`] does this too now, via a real
//!   ES-module resolver + QuickJS's own linker (see
//!   `plan/design-qjs-module-imports.md`), not a hand-written walker.
//! - **Still open, confirmed by testing, not assumed**: rh's version
//!   *also* validates every shipped-API reference against a static
//!   catalog (`crates/agenterm-rh/src/api_validate.rs`,
//!   `shipped_surfaces.rs`) — e.g. `fn entry() {
//!   std::fs::not_shipped(...) }` fails rh's check even though it's
//!   syntactically valid. qjs's `check_with_project_validation` has no
//!   equivalent: `check`ing a script that calls
//!   `__host.fleet_call('tabs.totallyNotARealOperation', '{}')` currently
//!   returns `ok` (verified against the real binary, not inferred) —
//!   there's no shipped-operation catalog wired into check for qjs, and
//!   `fleet_call`'s operation id is a plain runtime string, not something
//!   `Module::declare` can statically catch the way it catches syntax
//!   errors. Closing this needs a shared/exported operation catalog
//!   (`shipped_surfaces.rs` is rh-internal Rust today, not a portable
//!   format) plus a JS-source scanner for `__host.fleet_call('literal',
//!   ...)` call sites — and even then, only *string-literal* operation
//!   ids are staticly checkable; a computed id
//!   (`__host.fleet_call(someVariable, ...)`) can't be, which rh's own
//!   textual scanner presumably has the same limitation for. Not started.

use std::path::Path;

use rquickjs::loader::ScriptLoader;
use rquickjs::{CatchResultExt, Context, Module, Runtime};

use crate::error::QjsError;
use crate::module_resolver::ProjectModuleResolver;
use crate::module_sniff::wants_module_mode;

/// Parse/compile `source` as an ES module without executing it. `label` is
/// used only for QuickJS's own error messages (filename in a stack trace),
/// not for any path resolution — callers own path safety themselves (see
/// `check_many`, which resolves/validates paths before calling this).
///
/// No project root is known here, so no module loader is registered — a
/// script using `import`/`export` will fail with a "could not load
/// module" error regardless of whether the imported file exists. Callers
/// that have a real project root should use
/// [`check_with_project_validation`] instead, which resolves imports (and,
/// as a consequence of ES modules' own linking behavior, validates every
/// file in the import graph — see
/// `plan/design-qjs-module-imports.md` §4.3).
pub fn check(source: &str, label: &str) -> Result<(), QjsError> {
    let runtime = Runtime::new().map_err(|err| QjsError::Check(err.to_string()))?;
    let context = Context::full(&runtime).map_err(|err| QjsError::Check(err.to_string()))?;
    context.with(
        |ctx| match Module::declare(ctx.clone(), label, source).catch(&ctx) {
            Ok(_module) => Ok(()),
            // .catch() turns the generic "Exception generated by QuickJS" into
            // the actual thrown SyntaxError's message (line/column, what token
            // was unexpected) — without it every syntax error looks identical
            // and useless for a human or CI log to act on.
            Err(err) => Err(QjsError::Parse(err.to_string())),
        },
    )
}

/// Same "parse/declare, don't execute" contract as [`check`], but with a
/// project root: scripts that don't use `import`/`export`
/// ([`wants_module_mode`] is `false`) behave *exactly* like plain
/// `check()` — same call, same result, not a reimplementation — so this is
/// purely additive, never a behavior change for existing non-module
/// scripts. Scripts that do use `import`/`export` get a real,
/// root-confined module resolver (`module_resolver.rs`) registered before
/// `Module::declare`, so `check` on a multi-file project actually resolves
/// (and, since `Module::declare` eagerly links the whole static import
/// graph, recursively parse-validates) every file it imports — named
/// "aligned with rh" deliberately: this is qjs's answer to
/// `agenterm_rh::check_with_project_validation`'s *import-graph* half,
/// same name, different mechanism (rh hand-walks its own import graph;
/// qjs lets QuickJS's real module linker do it). It is **not** the whole
/// contract yet — rh's version also validates shipped-API references
/// (`std::fs::not_shipped(...)` fails rh's check even though it parses);
/// qjs has no equivalent (a script calling a nonexistent
/// `__host.fleet_call('made.up', ...)` operation still passes this
/// function's check). See this file's module doc for the full,
/// re-verified gap note — don't read "aligned with rh" here as "fully
/// equivalent to rh's function of the same name".
///
/// `label` here, unlike plain `check()`, **is** used for path resolution
/// (it's the base every relative import in `source` resolves against) —
/// so it must be a real file, and `entry_path`/`project_root` get the same
/// canonicalize-and-confine treatment `eval_module.rs` applies (same
/// reasoning: don't trust the caller to have gotten this right, guarantee
/// it here).
pub fn check_with_project_validation(
    source: &str,
    label: &Path,
    project_root: &Path,
) -> Result<(), QjsError> {
    if !wants_module_mode(source) {
        return check(source, &label.to_string_lossy());
    }

    let canonical_root = std::fs::canonicalize(project_root).map_err(|err| {
        QjsError::Usage(format!(
            "qjs_module_root: {}: {err}",
            project_root.display()
        ))
    })?;
    let canonical_label = std::fs::canonicalize(label)
        .map_err(|err| QjsError::Usage(format!("qjs_module_entry: {}: {err}", label.display())))?;
    if !canonical_label.starts_with(&canonical_root) {
        return Err(QjsError::Usage(format!(
            "qjs_module_entry_outside_root: {} is not inside {}",
            canonical_label.display(),
            canonical_root.display()
        )));
    }

    let runtime = Runtime::new().map_err(|err| QjsError::Check(err.to_string()))?;
    runtime.set_loader(
        ProjectModuleResolver::new(canonical_root),
        ScriptLoader::default().with_extension("mjs"),
    );
    let context = Context::full(&runtime).map_err(|err| QjsError::Check(err.to_string()))?;
    let label_str = canonical_label.to_string_lossy().into_owned();
    context.with(
        |ctx| match Module::declare(ctx.clone(), label_str.as_str(), source).catch(&ctx) {
            Ok(_module) => Ok(()),
            Err(err) => Err(QjsError::Parse(err.to_string())),
        },
    )
}

#[cfg(test)]
mod tests {
    use super::{check, check_with_project_validation};
    use tempfile::TempDir;

    #[test]
    fn accepts_valid_module_source() {
        check("export default 40 + 2;", "ok.js").expect("valid module source");
    }

    #[test]
    fn rejects_syntax_errors() {
        let error = check("this is not valid js (((", "bad.js").expect_err("syntax error");
        assert!(matches!(error, super::QjsError::Parse(_)));
    }

    #[test]
    fn does_not_execute_top_level_side_effects() {
        // If check() ran the module body, this would leave a trace we could
        // detect; since each check() call is its own fresh Runtime/Context,
        // the only way to observe "did it run" is within one call — proven
        // directly against rquickjs in the QJS-M1 spike (module_declare_probe,
        // since removed) and re-asserted here at the check() API boundary via
        // a script that would throw if executed but not if merely parsed.
        check(
            "if (true) { throw new Error('should not run'); }",
            "throws.js",
        )
        .expect("declare-only check must not execute the throwing statement");
    }

    #[test]
    fn with_project_validation_behaves_identically_for_non_module_scripts() {
        // No import/export -> must delegate straight to plain check(),
        // zero behavior change, even with a bogus/nonexistent project
        // root (which would fail immediately if this path tried to
        // canonicalize it — proving the delegation happens before any of
        // that, not just that it happens to produce the same answer).
        let dir = TempDir::new().expect("tempdir");
        let label = dir.path().join("does_not_exist_as_a_file.js");
        check_with_project_validation(
            "function entry() { return 1; }",
            &label,
            std::path::Path::new("/this/project/root/does/not/exist"),
        )
        .expect("non-module scripts skip project validation entirely");
    }

    #[test]
    fn with_project_validation_recursively_checks_a_real_import_graph() {
        let dir = TempDir::new().expect("tempdir");
        std::fs::write(dir.path().join("leaf.js"), "export const value = 42;").unwrap();
        let entry_path = dir.path().join("entry.js");
        std::fs::write(
            &entry_path,
            "import { value } from './leaf.js';\nfunction entry() { return value; }",
        )
        .unwrap();
        let source = std::fs::read_to_string(&entry_path).unwrap();
        check_with_project_validation(&source, &entry_path, dir.path())
            .expect("valid multi-file import graph must check clean");
    }

    #[test]
    fn with_project_validation_catches_a_syntax_error_in_an_imported_file() {
        let dir = TempDir::new().expect("tempdir");
        std::fs::write(dir.path().join("leaf.js"), "export const value = ((( ;").unwrap();
        let entry_path = dir.path().join("entry.js");
        std::fs::write(
            &entry_path,
            "import { value } from './leaf.js';\nfunction entry() { return value; }",
        )
        .unwrap();
        let source = std::fs::read_to_string(&entry_path).unwrap();
        let error = check_with_project_validation(&source, &entry_path, dir.path())
            .expect_err("a syntax error in an imported file must fail check, not just parse ok");
        assert!(matches!(error, super::QjsError::Parse(_)));
    }

    #[test]
    fn with_project_validation_rejects_an_import_that_escapes_the_root() {
        let outer = TempDir::new().expect("tempdir");
        std::fs::write(outer.path().join("secret.js"), "export const value = 1;").unwrap();
        let inner = outer.path().join("project");
        std::fs::create_dir_all(&inner).unwrap();
        let entry_path = inner.join("entry.js");
        std::fs::write(
            &entry_path,
            "import { value } from '../secret.js';\nfunction entry() { return value; }",
        )
        .unwrap();
        let source = std::fs::read_to_string(&entry_path).unwrap();
        let error = check_with_project_validation(&source, &entry_path, &inner)
            .expect_err("root-escaping import must fail check");
        assert!(
            error.to_string().contains("Error resolving module"),
            "{error}"
        );
    }

    #[test]
    fn known_gap_check_does_not_yet_validate_shipped_api_references() {
        // This is a GAP MARKER, not a feature test — it locks in the
        // current, known-incomplete behavior described in this file's
        // module doc (QJS-M6, not started) so the gap is a visible,
        // permanent fact instead of a claim that could quietly drift.
        // `agenterm_rh::check_with_project_validation` rejects a script
        // calling a shipped-API-unknown reference
        // (`std::fs::not_shipped(...)`, see
        // `crates/agenterm-rh/tests`/`api_validate.rs`'s own tests) even
        // though it's syntactically valid; qjs's version does not, and
        // this test proves that's still true right now, not asserted from
        // memory. If this test starts failing, that's QJS-M6 having
        // landed — update this test (and the module/function doc "known
        // gap" notes above) to match, don't just delete the inconvenient
        // assertion.
        let dir = TempDir::new().expect("tempdir");
        let entry_path = dir.path().join("entry.js");
        std::fs::write(
            &entry_path,
            "function entry() { return __host.fleet_call('tabs.totallyNotARealOperation', '{}'); }",
        )
        .unwrap();
        let source = std::fs::read_to_string(&entry_path).unwrap();
        check_with_project_validation(&source, &entry_path, dir.path())
            .expect("known gap: an unshipped fleet_call operation id is NOT caught by check yet");
    }
}
