use rhai::{AST, Expr, ScriptFuncDef, Stmt, StmtBlock, Token};

use crate::{subset::validate_ast, RhError};

pub fn transpile(source: &str) -> Result<String, RhError> {
    let ast = parse(source)?;
    validate_ast(&ast)?;
    emit(&ast)
}

fn parse(source: &str) -> Result<AST, RhError> {
    rhai::Engine::new()
        .compile(source)
        .map_err(|err| RhError::Parse(err.to_string()))
}

fn emit(ast: &AST) -> Result<String, RhError> {
    let mut out = String::from(
        "// Generated by agenterm-rh — do not edit.\n\
         #![allow(clippy::all, dead_code, unused_variables)]\n\n\
         use rhai::Dynamic;\n\n",
    );

    let mut wrote_fn = false;
    for meta in ast.iter_functions() {
        let Some(def) = find_fn_def(ast, meta.name) else {
            return Err(RhError::Transpile(format!(
                "missing body for function `{}`",
                meta.name
            )));
        };
        emit_fn(&mut out, def)?;
        wrote_fn = true;
    }

    if !wrote_fn {
        out.push_str("pub fn rh_entry() -> Dynamic {\n    Dynamic::UNIT\n}\n");
    } else {
        out.push_str("\npub fn rh_entry() -> Dynamic {\n    Dynamic::UNIT\n}\n");
    }

    Ok(out)
}

fn find_fn_def<'a>(ast: &'a AST, name: &str) -> Option<&'a ScriptFuncDef> {
    ast.iter_fn_def()
        .find(|def| def.name == name)
        .map(|def| def.as_ref())
}

fn emit_fn(out: &mut String, def: &ScriptFuncDef) -> Result<(), RhError> {
    out.push_str("pub fn ");
    out.push_str(def.name.as_str());
    out.push('(');
    for (index, param) in def.params.iter().enumerate() {
        if index > 0 {
            out.push_str(", ");
        }
        out.push_str("mut ");
        out.push_str(param.as_str());
        out.push_str(": Dynamic");
    }
    out.push_str(") -> Dynamic {\n");
    emit_block(out, &def.body, true)?;
    out.push_str("}\n\n");
    Ok(())
}

fn emit_block(out: &mut String, block: &StmtBlock, implicit_return: bool) -> Result<(), RhError> {
    let stmts: Vec<_> = block.iter().collect();
    for (index, stmt) in stmts.iter().enumerate() {
        let is_last = index + 1 == stmts.len();
        emit_stmt(out, stmt, implicit_return && is_last)?;
    }
    Ok(())
}

fn emit_stmt(out: &mut String, stmt: &Stmt, implicit_return: bool) -> Result<(), RhError> {
    match stmt {
        Stmt::Var(boxed, ..) => {
            let (ident, expr, _) = boxed.as_ref();
            out.push_str("    let ");
            out.push_str(ident.name.as_str());
            out.push_str(" = ");
            emit_expr(out, expr)?;
            out.push_str(";\n");
        }
        Stmt::Return(Some(expr), ..) => {
            out.push_str("    return ");
            emit_expr(out, expr)?;
            out.push_str(";\n");
        }
        Stmt::Return(None, ..) => out.push_str("    return Dynamic::UNIT;\n"),
        Stmt::If(boxed, ..) => {
            let flow = boxed.as_ref();
            out.push_str("    if ");
            emit_expr(out, &flow.expr)?;
            out.push_str(" {\n");
            emit_block(out, &flow.body, true)?;
            out.push_str("    }");
            if !flow.branch.is_empty() {
                out.push_str(" else {\n");
                emit_block(out, &flow.branch, true)?;
                out.push_str("    }\n");
            } else {
                out.push('\n');
            }
        }
        Stmt::Block(boxed) => {
            out.push_str("    {\n");
            emit_block(out, boxed, implicit_return)?;
            out.push_str("    }\n");
        }
        Stmt::Expr(expr) if implicit_return => {
            out.push_str("    return ");
            emit_expr(out, expr)?;
            out.push_str(";\n");
        }
        Stmt::Expr(expr) => {
            emit_expr(out, expr)?;
            out.push_str(";\n");
        }
        Stmt::FnCall(call, ..) if implicit_return => {
            out.push_str("    return ");
            emit_call(out, call)?;
            out.push_str(";\n");
        }
        Stmt::FnCall(call, ..) => {
            emit_call(out, call)?;
            out.push_str(";\n");
        }
        Stmt::Noop(..) => {}
        other => {
            return Err(RhError::Transpile(format!(
                "unsupported statement in rh-0: {other:?}"
            )));
        }
    }
    Ok(())
}

fn emit_expr(out: &mut String, expr: &Expr) -> Result<(), RhError> {
    match expr {
        Expr::IntegerConstant(value, ..) => {
            out.push_str("Dynamic::from(");
            out.push_str(&value.to_string());
            out.push(')');
        }
        Expr::BoolConstant(value, ..) => {
            out.push_str("Dynamic::from(");
            out.push_str(if *value { "true" } else { "false" });
            out.push(')');
        }
        Expr::StringConstant(value, ..) => {
            out.push_str("Dynamic::from(");
            out.push_str(&format!("{value:?}"));
            out.push(')');
        }
        Expr::Unit(..) => out.push_str("Dynamic::UNIT"),
        Expr::Variable(ident, ..) => out.push_str(ident.1.as_str()),
        Expr::FnCall(call, ..) => emit_call(out, call)?,
        Expr::Stmt(block) => {
            out.push_str("{ ");
            emit_block(out, block, true)?;
            out.push_str(" }");
        }
        other => {
            return Err(RhError::Transpile(format!(
                "unsupported expression in rh-0: {other:?}"
            )));
        }
    }
    Ok(())
}

fn emit_call(out: &mut String, call: &rhai::FnCallExpr) -> Result<(), RhError> {
    if let Some(op) = &call.op_token {
        return emit_op(out, op, &call.args);
    }
    if call.name == "print" {
        out.push_str("println!(");
        for (index, arg) in call.args.iter().enumerate() {
            if index > 0 {
                out.push_str(", ");
            }
            emit_expr(out, arg)?;
        }
        out.push(')');
        return Ok(());
    }
    Err(RhError::Transpile(format!(
        "unsupported call `{}` in rh-0",
        call.name
    )))
}

fn emit_op(out: &mut String, op: &Token, args: &[Expr]) -> Result<(), RhError> {
    match (op, args.len()) {
        (Token::Plus, 2) => binary(out, "+", &args[0], &args[1]),
        (Token::Minus, 2) => binary(out, "-", &args[0], &args[1]),
        (Token::Multiply, 2) => binary(out, "*", &args[0], &args[1]),
        (Token::Divide, 2) => binary(out, "/", &args[0], &args[1]),
        (Token::Modulo, 2) => binary(out, "%", &args[0], &args[1]),
        (Token::Equals, 2) => binary(out, "==", &args[0], &args[1]),
        (Token::NotEqualsTo, 2) => binary(out, "!=", &args[0], &args[1]),
        (Token::GreaterThan, 2) => binary(out, ">", &args[0], &args[1]),
        (Token::GreaterThanEqualsTo, 2) => binary(out, ">=", &args[0], &args[1]),
        (Token::LessThan, 2) => binary(out, "<", &args[0], &args[1]),
        (Token::LessThanEqualsTo, 2) => binary(out, "<=", &args[0], &args[1]),
        (Token::And, 2) => binary(out, "&&", &args[0], &args[1]),
        (Token::Or, 2) => binary(out, "||", &args[0], &args[1]),
        (Token::Minus, 1) => {
            out.push_str("(-(");
            emit_expr(out, &args[0])?;
            out.push_str("))");
            Ok(())
        }
        (Token::Bang, 1) => {
            out.push_str("(!(");
            emit_expr(out, &args[0])?;
            out.push_str("))");
            Ok(())
        }
        _ => Err(RhError::Transpile(format!(
            "unsupported operator `{op:?}` in rh-0"
        ))),
    }
}

fn binary(out: &mut String, op: &str, lhs: &Expr, rhs: &Expr) -> Result<(), RhError> {
    out.push('(');
    emit_expr(out, lhs)?;
    out.push(' ');
    out.push_str(op);
    out.push(' ');
    emit_expr(out, rhs)?;
    out.push(')');
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::transpile;

    #[test]
    fn transpiles_add_fn() {
        let rust = transpile("fn add(a, b) { a + b }").expect("transpile");
        assert!(rust.contains("pub fn add"));
        assert!(rust.contains("a + b"));
    }
}
