use std::collections::BTreeMap;

use rhai::{AST, ASTFlags, Expr, ScriptFuncDef, Stmt, StmtBlock, Token};

use crate::{
    RhError,
    expr_print::{
        args_index_expr, expr_to_rhai, is_args_len_expr, is_pure_int_expr, is_var_len_expr,
        uses_host_surface, var_len_name,
    },
    fleet::{fleet_params_json, parse_fleet_call, validate_fleet_call},
    host_api::{emit_host_runtime, rust_raw_string_literal},
    subset::{compat_validate, validate_ast},
};

#[derive(Clone, Copy, PartialEq, Eq)]
enum ValueKind {
    Int,
    Bool,
    String,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum CdylibExecutionMode {
    Native,
    HostEval,
    CompatDelegating,
}

impl CdylibExecutionMode {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Native => "native",
            Self::HostEval => "host-eval",
            Self::CompatDelegating => "compat-delegating",
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct CdylibTranspileOutput {
    pub rust: String,
    pub execution_mode: CdylibExecutionMode,
}

#[derive(Clone)]
struct EmitCtx {
    cdylib: bool,
    scope: BTreeMap<String, ValueKind>,
    try_depth: u32,
}

impl EmitCtx {
    fn new(cdylib: bool) -> Self {
        Self {
            cdylib,
            scope: BTreeMap::new(),
            try_depth: 0,
        }
    }

    fn in_try(&self) -> bool {
        self.cdylib && self.try_depth > 0
    }

    fn enter_try(mut self) -> Self {
        self.try_depth += 1;
        self
    }

    fn value_type(&self) -> &'static str {
        if self.cdylib { "INT" } else { "Dynamic" }
    }

    fn unit_expr(&self) -> &'static str {
        if self.cdylib { "0" } else { "Dynamic::UNIT" }
    }

    fn emit_scope_json_expr(&self, out: &mut String) {
        if self.scope.is_empty() {
            out.push_str("\"{}\"");
            return;
        }
        out.push_str("&format!(\"{{\\\"vars\\\":{{");
        let mut first = true;
        for (name, kind) in &self.scope {
            if !first {
                out.push(',');
            }
            first = false;
            match kind {
                ValueKind::Int => {
                    out.push_str(&format!(
                        "\\\"{name}\\\":{{\\\"kind\\\":\\\"int\\\",\\\"value\\\":{{}}}}"
                    ));
                }
                ValueKind::Bool => {
                    out.push_str(&format!(
                        "\\\"{name}\\\":{{\\\"kind\\\":\\\"bool\\\",\\\"value\\\":{{}}}}"
                    ));
                }
                ValueKind::String => {
                    out.push_str(&format!(
                        "\\\"{name}\\\":{{\\\"kind\\\":\\\"string\\\",\\\"value\\\":{{}}}}"
                    ));
                }
            }
        }
        out.push_str("}}}}\"");
        for (name, kind) in &self.scope {
            out.push_str(", ");
            if *kind == ValueKind::String {
                out.push_str("serde_json::to_string(&");
                out.push_str(name);
                out.push_str(").unwrap_or_else(|_| \"\\\"\\\"\".to_owned())");
            } else {
                out.push_str(name);
            }
        }
        out.push(')');
    }

    fn with_binding(mut self, name: &str, kind: ValueKind) -> Self {
        self.scope.insert(name.to_owned(), kind);
        self
    }
}

pub fn transpile(source: &str) -> Result<String, RhError> {
    let ast = parse(source)?;
    validate_ast(&ast)?;
    emit(&ast, EmitCtx::new(false))
}

pub fn transpile_cdylib(source: &str) -> Result<String, RhError> {
    Ok(transpile_cdylib_with_mode(source)?.rust)
}

pub fn transpile_cdylib_with_mode(source: &str) -> Result<CdylibTranspileOutput, RhError> {
    let ast = parse(source)?;
    if validate_ast(&ast).is_ok() {
        if let Ok(rust) = emit(&ast, EmitCtx::new(true)) {
            let execution_mode = if rust.matches("rh_host_eval_int(").count() > 1 {
                CdylibExecutionMode::HostEval
            } else {
                CdylibExecutionMode::Native
            };
            return Ok(CdylibTranspileOutput {
                rust,
                execution_mode,
            });
        }
    }
    compat_validate(source, &ast)?;
    Ok(CdylibTranspileOutput {
        rust: emit_compat_delegating(source)?,
        execution_mode: CdylibExecutionMode::CompatDelegating,
    })
}

fn emit_compat_delegating(source: &str) -> Result<String, RhError> {
    let mut out = String::from(
        "// Generated by agenterm-rh (compat delegating) — do not edit.\n\
         #![allow(clippy::all, dead_code, unused_variables)]\n\n\
         type INT = i64;\n\n",
    );
    emit_host_runtime(&mut out);
    out.push_str("const RH_SCRIPT_SOURCE: &str = ");
    out.push_str(&rust_raw_string_literal(source));
    out.push_str(
        ";\n\n\
         fn rh_entry_internal() -> INT {\n\
             rh_host_run_script(RH_SCRIPT_SOURCE)\n\
         }\n\n\
         #[no_mangle]\n\
         pub extern \"C\" fn rh_pack_api_version() -> u32 {\n    1\n}\n\n\
         #[no_mangle]\n\
         pub extern \"C\" fn rh_entry() -> i64 {\n\
             rh_entry_internal() as i64\n\
         }\n",
    );
    Ok(out)
}

fn parse(source: &str) -> Result<AST, RhError> {
    crate::check::parse_rh_ast(source)
}

fn emit(ast: &AST, ctx: EmitCtx) -> Result<String, RhError> {
    let mut out = String::from(
        "// Generated by agenterm-rh — do not edit.\n\
         #![allow(clippy::all, dead_code, unused_variables)]\n\n",
    );
    if ctx.cdylib {
        out.push_str("type INT = i64;\n\n");
        emit_host_runtime(&mut out);
    } else {
        out.push_str("use rhai::Dynamic;\n\n");
    }

    let mut wrote_fn = false;
    let mut has_entry = false;
    for meta in ast.iter_functions() {
        if meta.name == "entry" {
            has_entry = true;
        }
        if ctx.cdylib && meta.name == "cc_lines" {
            let Some(def) = find_fn_def(ast, meta.name) else {
                return Err(RhError::Transpile("missing cc_lines body".into()));
            };
            emit_cc_lines_exports(&mut out, def)?;
            wrote_fn = true;
            continue;
        }
        let Some(def) = find_fn_def(ast, meta.name) else {
            return Err(RhError::Transpile(format!(
                "missing body for function `{}`",
                meta.name
            )));
        };
        emit_fn(&mut out, def, &mut EmitCtx::new(ctx.cdylib))?;
        wrote_fn = true;
    }

    if ctx.cdylib {
        out.push_str("fn rh_entry_internal() -> INT {\n");
        if has_entry {
            out.push_str("    entry()\n");
        } else {
            out.push_str("    0\n");
        }
        out.push_str("}\n\n");
        out.push_str(
            "#[no_mangle]\npub extern \"C\" fn rh_pack_api_version() -> u32 {\n    1\n}\n\n",
        );
        out.push_str("#[no_mangle]\npub extern \"C\" fn rh_entry() -> i64 {\n");
        out.push_str("    rh_entry_internal() as i64\n");
        out.push_str("}\n");
    } else if !wrote_fn {
        out.push_str("pub fn rh_entry() -> Dynamic {\n    Dynamic::UNIT\n}\n");
    } else {
        out.push_str("\npub fn rh_entry() -> Dynamic {\n    Dynamic::UNIT\n}\n");
    }

    Ok(out)
}

pub fn cc_line_count(source: &str) -> Option<u32> {
    let ast = parse(source).ok()?;
    let def = find_fn_def(&ast, "cc_lines")?;
    let lines = extract_cc_lines(def).ok()?;
    u32::try_from(lines.len()).ok()
}

fn extract_cc_lines(def: &ScriptFuncDef) -> Result<Vec<String>, RhError> {
    let expr = single_expression(&def.body)?;
    extract_string_array_expr(expr)
}

fn extract_string_array_expr(expr: &Expr) -> Result<Vec<String>, RhError> {
    match expr {
        Expr::Array(items, ..) => items.iter().map(string_literal_expr).collect(),
        Expr::DynamicConstant(value, ..) => {
            if !value.is_array() {
                return Err(RhError::Transpile(
                    "cc_lines must return a string array literal".into(),
                ));
            }
            let array = value.clone().into_array().map_err(|_| {
                RhError::Transpile("cc_lines must return a string array literal".into())
            })?;
            array.iter().map(dynamic_string).collect()
        }
        _ => Err(RhError::Transpile(
            "cc_lines must return a string array literal".into(),
        )),
    }
}

fn string_literal_expr(expr: &Expr) -> Result<String, RhError> {
    match expr {
        Expr::StringConstant(value, ..) => Ok(value.to_string()),
        _ => Err(RhError::Transpile(
            "cc_lines array must contain string literals only".into(),
        )),
    }
}

fn dynamic_string(value: &rhai::Dynamic) -> Result<String, RhError> {
    value
        .clone()
        .into_string()
        .map_err(|_| RhError::Transpile("cc_lines array must contain strings only".into()))
}

pub(crate) fn single_expression(body: &StmtBlock) -> Result<&Expr, RhError> {
    let mut iter = body.iter();
    let Some(stmt) = iter.next() else {
        return Err(RhError::Transpile(
            "cc_lines must return a string array literal".into(),
        ));
    };
    if iter.next().is_some() {
        return Err(RhError::Transpile(
            "cc_lines must contain a single return expression".into(),
        ));
    }
    match stmt {
        Stmt::Expr(expr) => Ok(expr.as_ref()),
        Stmt::Return(Some(expr), ..) => Ok(expr.as_ref()),
        Stmt::Block(block) => single_expression(block),
        _ => Err(RhError::Transpile(
            "cc_lines must return a string array literal".into(),
        )),
    }
}

fn emit_cc_lines_exports(out: &mut String, def: &ScriptFuncDef) -> Result<(), RhError> {
    let lines = extract_cc_lines(def)?;
    let count = lines.len();
    out.push_str("static RH_CC_LINES: [&str; ");
    out.push_str(&count.to_string());
    out.push_str("] = [");
    for (index, line) in lines.iter().enumerate() {
        if index > 0 {
            out.push_str(", ");
        }
        out.push_str(&format!("{line:?}"));
    }
    out.push_str("];\n\n");
    out.push_str("#[no_mangle]\npub extern \"C\" fn rh_cc_line_count() -> u32 {\n    ");
    out.push_str(&count.to_string());
    out.push_str("\n}\n\n");
    out.push_str("#[no_mangle]\npub extern \"C\" fn rh_cc_line_len(i: u32) -> u32 {\n");
    out.push_str("    if (i as usize) >= RH_CC_LINES.len() {\n        return 0;\n    }\n");
    out.push_str("    RH_CC_LINES[i as usize].len() as u32\n}\n\n");
    out.push_str("#[no_mangle]\npub extern \"C\" fn rh_cc_line_ptr(i: u32) -> *const u8 {\n");
    out.push_str(
        "    if (i as usize) >= RH_CC_LINES.len() {\n        return std::ptr::null();\n    }\n",
    );
    out.push_str("    RH_CC_LINES[i as usize].as_ptr()\n}\n\n");
    Ok(())
}

fn find_fn_def<'a>(ast: &'a AST, name: &str) -> Option<&'a ScriptFuncDef> {
    ast.iter_fn_def()
        .find(|def| def.name == name)
        .map(|def| def.as_ref())
}

fn emit_fn(out: &mut String, def: &ScriptFuncDef, ctx: &mut EmitCtx) -> Result<(), RhError> {
    let mut fn_ctx = ctx.clone();
    for param in &def.params {
        fn_ctx = fn_ctx.with_binding(param.as_str(), ValueKind::Int);
    }
    out.push_str("pub fn ");
    out.push_str(def.name.as_str());
    out.push('(');
    for (index, param) in def.params.iter().enumerate() {
        if index > 0 {
            out.push_str(", ");
        }
        if fn_ctx.cdylib {
            out.push_str(param.as_str());
            out.push_str(": INT");
        } else {
            out.push_str("mut ");
            out.push_str(param.as_str());
            out.push_str(": Dynamic");
        }
    }
    out.push_str(") -> ");
    out.push_str(fn_ctx.value_type());
    out.push_str(" {\n");
    emit_block(out, &def.body, &mut fn_ctx, true)?;
    out.push_str("}\n\n");
    Ok(())
}

fn emit_block(
    out: &mut String,
    block: &StmtBlock,
    ctx: &mut EmitCtx,
    implicit_return: bool,
) -> Result<(), RhError> {
    let stmts: Vec<_> = block.iter().collect();
    for (index, stmt) in stmts.iter().enumerate() {
        let is_last = index + 1 == stmts.len();
        emit_stmt(out, stmt, ctx, implicit_return && is_last)?;
    }
    Ok(())
}

fn emit_stmt(
    out: &mut String,
    stmt: &Stmt,
    ctx: &mut EmitCtx,
    implicit_return: bool,
) -> Result<(), RhError> {
    match stmt {
        Stmt::Var(boxed, ..) => {
            let (ident, expr, _) = boxed.as_ref();
            let kind = infer_binding_kind(expr);
            out.push_str("    let mut ");
            out.push_str(ident.name.as_str());
            out.push_str(" = ");
            emit_expr(out, expr, ctx)?;
            out.push_str(";\n");
            *ctx = ctx.clone().with_binding(ident.name.as_str(), kind);
        }
        Stmt::Assignment(boxed, ..) => {
            let (op, bin) = boxed.as_ref();
            let Expr::Variable(ident, ..) = &bin.lhs else {
                return Err(RhError::Transpile(
                    "assignment lhs must be a variable".into(),
                ));
            };
            out.push_str("    ");
            out.push_str(ident.1.as_str());
            if let Some((_, _, _, syntax, _, _)) = op.get_op_assignment_info() {
                out.push(' ');
                out.push_str(syntax);
                out.push(' ');
            } else {
                out.push_str(" = ");
            }
            emit_expr(out, &bin.rhs, ctx)?;
            out.push_str(";\n");
        }
        Stmt::Return(Some(expr), ..) => {
            out.push_str("    return ");
            emit_expr(out, expr, ctx)?;
            out.push_str(";\n");
        }
        Stmt::Return(None, ..) => {
            out.push_str("    return ");
            out.push_str(ctx.unit_expr());
            out.push_str(";\n");
        }
        Stmt::If(boxed, ..) => {
            let flow = boxed.as_ref();
            out.push_str("    if ");
            emit_expr(out, &flow.expr, ctx)?;
            out.push_str(" != 0 {\n");
            emit_block(out, &flow.body, ctx, true)?;
            out.push_str("    }");
            if !flow.branch.is_empty() {
                out.push_str(" else {\n");
                emit_block(out, &flow.branch, ctx, true)?;
                out.push_str("    }\n");
            } else {
                out.push('\n');
            }
        }
        Stmt::For(boxed, ..) => {
            let (counter, _, flow) = boxed.as_ref();
            if let Some(plan) = int_for_plan(&flow.expr) {
                match plan {
                    IntForPlan::Values(items) => {
                        out.push_str("    for ");
                        out.push_str(counter.name.as_str());
                        out.push_str(" in [");
                        for (index, item) in items.iter().enumerate() {
                            if index > 0 {
                                out.push_str(", ");
                            }
                            out.push_str(&item.to_string());
                        }
                        out.push_str("].iter().copied() {\n");
                    }
                    IntForPlan::Exclusive { start, end } => {
                        out.push_str("    for ");
                        out.push_str(counter.name.as_str());
                        out.push_str(" in ");
                        emit_for_bound(out, &start, ctx)?;
                        out.push_str("..");
                        emit_for_bound(out, &end, ctx)?;
                        out.push_str(" {\n");
                    }
                    IntForPlan::Inclusive { start, end } => {
                        out.push_str("    for ");
                        out.push_str(counter.name.as_str());
                        out.push_str(" in ");
                        emit_for_bound(out, &start, ctx)?;
                        out.push_str("..=");
                        emit_for_bound(out, &end, ctx)?;
                        out.push_str(" {\n");
                    }
                }
                let mut loop_ctx = ctx
                    .clone()
                    .with_binding(counter.name.as_str(), ValueKind::Int);
                emit_block(out, &flow.body, &mut loop_ctx, false)?;
                out.push_str("    }\n");
            } else {
                let snippet = crate::expr_print::stmt_to_rhai(stmt)?;
                out.push_str("    let _for = rh_host_eval_int(");
                out.push_str(&format!("{:?}, ", snippet));
                ctx.emit_scope_json_expr(out);
                out.push_str(";\n");
            }
        }
        Stmt::While(boxed, ..) => {
            let flow = boxed.as_ref();
            if is_pure_int_expr(&flow.expr) {
                out.push_str("    while ");
                emit_expr(out, &flow.expr, ctx)?;
                out.push_str(" != 0 {\n");
                emit_block(out, &flow.body, ctx, false)?;
                out.push_str("    }\n");
            } else {
                let snippet = crate::expr_print::stmt_to_rhai(stmt)?;
                out.push_str("    let _while = rh_host_eval_int(");
                out.push_str(&format!("{:?}, ", snippet));
                ctx.emit_scope_json_expr(out);
                out.push_str(";\n");
            }
        }
        Stmt::TryCatch(boxed, ..) if ctx.cdylib => {
            let flow = boxed.as_ref();
            out.push_str("    match (|| -> Result<INT, INT> {\n");
            let mut try_ctx = ctx.clone().enter_try();
            emit_try_block(out, &flow.body, &mut try_ctx)?;
            out.push_str("    })() {\n");
            out.push_str("        Ok(__rh_try_v) => __rh_try_v,\n");
            out.push_str("        Err(_) => {\n");
            emit_block_tail_expr(out, &flow.branch, ctx)?;
            out.push_str("        }\n");
            out.push_str("    }\n");
        }
        Stmt::TryCatch(..) => {
            let snippet = crate::expr_print::stmt_to_rhai(stmt)?;
            out.push_str("    let _try = rh_host_eval_int(");
            out.push_str(&format!("{:?}, ", snippet));
            ctx.emit_scope_json_expr(out);
            out.push_str(";\n");
            if implicit_return {
                out.push_str("    return _try;\n");
            }
        }
        Stmt::Block(boxed) => {
            out.push_str("    {\n");
            emit_block(out, boxed, ctx, implicit_return)?;
            out.push_str("    }\n");
        }
        Stmt::Expr(expr) if implicit_return => {
            out.push_str("    return ");
            emit_expr(out, expr, ctx)?;
            out.push_str(";\n");
        }
        Stmt::Expr(expr) => {
            out.push_str("    ");
            emit_expr(out, expr, ctx)?;
            out.push_str(";\n");
        }
        Stmt::FnCall(call, ..) if call.name == "throw" => {
            emit_throw_stmt(out, call, ctx, implicit_return)?;
        }
        Stmt::FnCall(call, ..) if implicit_return => {
            out.push_str("    return ");
            emit_call(out, call, ctx)?;
            out.push_str(";\n");
        }
        Stmt::FnCall(call, ..) => {
            out.push_str("    ");
            emit_call(out, call, ctx)?;
            out.push_str(";\n");
        }
        Stmt::BreakLoop(expr, flags, ..) => {
            if expr.is_some() {
                return Err(RhError::Transpile(
                    "break/continue with value is not in rh-3".into(),
                ));
            }
            if flags.contains(ASTFlags::BREAK) {
                out.push_str("    break;\n");
            } else {
                out.push_str("    continue;\n");
            }
        }
        Stmt::Noop(..) => {}
        other => {
            return Err(RhError::Transpile(format!(
                "unsupported statement in rh-2: {other:?}"
            )));
        }
    }
    Ok(())
}

fn emit_block_tail_expr(
    out: &mut String,
    block: &StmtBlock,
    ctx: &mut EmitCtx,
) -> Result<(), RhError> {
    let stmts: Vec<_> = block.iter().collect();
    if stmts.is_empty() {
        out.push_str("            0\n");
        return Ok(());
    }
    for stmt in &stmts[..stmts.len() - 1] {
        let mut inner = String::new();
        emit_stmt(&mut inner, stmt, ctx, false)?;
        for line in inner.lines() {
            out.push_str("            ");
            out.push_str(line);
            out.push('\n');
        }
    }
    match stmts.last().expect("non-empty") {
        Stmt::Expr(expr) => {
            out.push_str("            ");
            emit_expr(out, expr, ctx)?;
            out.push('\n');
        }
        other => {
            let mut inner = String::new();
            emit_stmt(&mut inner, other, ctx, true)?;
            for line in inner.lines() {
                out.push_str("            ");
                out.push_str(line);
                out.push('\n');
            }
        }
    }
    Ok(())
}

fn emit_try_block(out: &mut String, block: &StmtBlock, ctx: &mut EmitCtx) -> Result<(), RhError> {
    let stmts: Vec<_> = block.iter().collect();
    if stmts.is_empty() {
        out.push_str("        Ok(0)\n");
        return Ok(());
    }
    for (index, stmt) in stmts.iter().enumerate() {
        let is_last = index + 1 == stmts.len();
        emit_try_stmt(out, stmt, ctx, is_last)?;
    }
    Ok(())
}

fn emit_try_stmt(
    out: &mut String,
    stmt: &Stmt,
    ctx: &mut EmitCtx,
    implicit_ok: bool,
) -> Result<(), RhError> {
    match stmt {
        Stmt::Expr(expr) if implicit_ok => {
            out.push_str("        return Ok(");
            emit_expr(out, expr, ctx)?;
            out.push_str(");\n");
        }
        Stmt::Return(Some(expr), flags, ..) if flags.contains(ASTFlags::BREAK) => {
            out.push_str("        return Err(");
            emit_expr(out, expr, ctx)?;
            out.push_str(");\n");
        }
        Stmt::BreakLoop(expr, flags, ..) => {
            if expr.is_some() {
                return Err(RhError::Transpile(
                    "break/continue with value is not in rh-3".into(),
                ));
            }
            if flags.contains(ASTFlags::BREAK) {
                out.push_str("        break;\n");
            } else {
                out.push_str("        continue;\n");
            }
        }
        Stmt::FnCall(call, ..) if call.name == "throw" => {
            out.push_str("        ");
            emit_throw_expr(out, call, ctx)?;
            out.push('\n');
        }
        other => {
            let mut inner = String::new();
            emit_stmt(&mut inner, other, ctx, false)?;
            for line in inner.lines() {
                out.push_str("        ");
                out.push_str(line);
                out.push('\n');
            }
            if implicit_ok {
                out.push_str("        Ok(0)\n");
            }
        }
    }
    Ok(())
}

fn emit_throw_stmt(
    out: &mut String,
    call: &rhai::FnCallExpr,
    ctx: &mut EmitCtx,
    implicit_return: bool,
) -> Result<(), RhError> {
    if ctx.in_try() {
        out.push_str("    ");
        emit_throw_expr(out, call, ctx)?;
        out.push('\n');
    } else {
        let snippet = format!(
            "throw {};",
            expr_to_rhai(&call.args[0]).unwrap_or_else(|_| "0".into())
        );
        out.push_str("    let _throw = rh_host_eval_int(");
        out.push_str(&format!("{:?}, ", snippet));
        ctx.emit_scope_json_expr(out);
        out.push_str(";\n");
        if implicit_return {
            out.push_str("    return _throw;\n");
        }
    }
    Ok(())
}

fn emit_throw_expr(
    out: &mut String,
    call: &rhai::FnCallExpr,
    ctx: &mut EmitCtx,
) -> Result<(), RhError> {
    if call.args.len() != 1 {
        return Err(RhError::Transpile("throw expects one argument".into()));
    }
    if ctx.in_try() && is_pure_int_expr(&call.args[0]) {
        out.push_str("return Err(");
        emit_expr(out, &call.args[0], ctx)?;
        out.push_str(");");
    } else {
        let snippet = format!(
            "throw {};",
            expr_to_rhai(&call.args[0]).unwrap_or_else(|_| "0".into())
        );
        out.push_str("return Err(rh_host_eval_int(");
        out.push_str(&format!("{:?}, ", snippet));
        ctx.emit_scope_json_expr(out);
        out.push_str(");");
    }
    Ok(())
}

fn infer_binding_kind(expr: &Expr) -> ValueKind {
    match expr {
        Expr::BoolConstant(..) => ValueKind::Bool,
        _ if args_index_expr(expr).is_some() => ValueKind::String,
        _ if std_fs_read_to_string_arg(expr).is_some() => ValueKind::String,
        _ if uses_host_surface(expr) => ValueKind::Bool,
        _ => ValueKind::Int,
    }
}

const MAX_NATIVE_FOR_SPAN: i64 = 4096;

#[derive(Debug, Clone)]
enum IntForBound {
    Const(i64),
    Expr(Expr),
}

#[derive(Debug, Clone)]
enum IntForPlan {
    Values(Vec<i64>),
    Exclusive {
        start: IntForBound,
        end: IntForBound,
    },
    Inclusive {
        start: IntForBound,
        end: IntForBound,
    },
}

fn int_for_bound(expr: &Expr) -> Option<IntForBound> {
    int_const(expr)
        .map(IntForBound::Const)
        .or_else(|| is_pure_int_expr(expr).then(|| IntForBound::Expr(expr.clone())))
}

fn emit_for_bound(out: &mut String, bound: &IntForBound, ctx: &mut EmitCtx) -> Result<(), RhError> {
    match bound {
        IntForBound::Const(value) => out.push_str(&value.to_string()),
        IntForBound::Expr(expr) => emit_expr(out, expr, ctx)?,
    }
    Ok(())
}

fn int_const(expr: &Expr) -> Option<i64> {
    match expr {
        Expr::IntegerConstant(value, ..) => Some(*value),
        _ => None,
    }
}

fn bounded_exclusive_span(start: i64, end: i64) -> Option<i64> {
    if end <= start {
        return Some(0);
    }
    let span = end.checked_sub(start)?;
    (span <= MAX_NATIVE_FOR_SPAN).then_some(span)
}

fn bounded_inclusive_span(start: i64, end: i64) -> Option<i64> {
    if end < start {
        return Some(0);
    }
    let span = end.checked_sub(start)?.checked_add(1)?;
    (span <= MAX_NATIVE_FOR_SPAN).then_some(span)
}

fn int_for_plan(iterable: &Expr) -> Option<IntForPlan> {
    if let Expr::Array(items, ..) = iterable {
        let mut values = Vec::new();
        for item in items {
            values.push(int_const(item)?);
        }
        return Some(IntForPlan::Values(values));
    }
    let Expr::FnCall(call, ..) = iterable else {
        return None;
    };
    if call.args.len() != 2 {
        return None;
    }
    let start = int_for_bound(&call.args[0])?;
    let end = int_for_bound(&call.args[1])?;
    let is_exclusive = call.name.as_str() == Token::ExclusiveRange.literal_syntax();
    let is_inclusive = call.name.as_str() == Token::InclusiveRange.literal_syntax();
    if !is_exclusive && !is_inclusive {
        return None;
    }
    if let (IntForBound::Const(start), IntForBound::Const(end)) = (&start, &end) {
        if is_exclusive {
            bounded_exclusive_span(*start, *end)?;
        } else {
            bounded_inclusive_span(*start, *end)?;
        }
    }
    if is_exclusive {
        Some(IntForPlan::Exclusive { start, end })
    } else {
        Some(IntForPlan::Inclusive { start, end })
    }
}

fn emit_host_expr(out: &mut String, expr: &Expr, ctx: &EmitCtx) -> Result<(), RhError> {
    let snippet = expr_to_rhai(expr)?;
    out.push_str("rh_host_eval_int(");
    out.push_str(&format!("{:?}, ", snippet));
    ctx.emit_scope_json_expr(out);
    out.push(')');
    Ok(())
}

fn std_fs_exists_arg(expr: &Expr) -> Option<&Expr> {
    std_fs_single_arg(expr, "exists")
}

fn std_fs_read_to_string_arg(expr: &Expr) -> Option<&Expr> {
    std_fs_single_arg(expr, "read_to_string")
}

fn std_fs_single_arg<'a>(expr: &'a Expr, name: &str) -> Option<&'a Expr> {
    let Expr::FnCall(call, ..) = expr else {
        return None;
    };
    if call.namespace.to_string() != "std::fs" || call.name != name || call.args.len() != 1 {
        return None;
    }
    Some(&call.args[0])
}

fn emit_expr(out: &mut String, expr: &Expr, ctx: &mut EmitCtx) -> Result<(), RhError> {
    if ctx.cdylib {
        if let Some(index) = args_index_expr(expr) {
            emit_args_index(out, index, ctx)?;
            return Ok(());
        }
        if let Some(path) = std_fs_exists_arg(expr)
            && emit_std_fs_exists(out, path, ctx)?
        {
            return Ok(());
        }
        if let Some(path) = std_fs_read_to_string_arg(expr)
            && emit_std_fs_read_to_string(out, path, ctx)?
        {
            return Ok(());
        }
        if emit_string_contains(out, expr, ctx) {
            return Ok(());
        }
        if let Some(call) = parse_fleet_call(expr) {
            validate_fleet_call(&call)?;
            let params = fleet_params_json(&call)?;
            out.push_str("rh_fleet_call(");
            out.push_str(&format!("{:?}, {:?}", call.operation_id, params));
            out.push(')');
            return Ok(());
        }
        if !is_pure_int_expr(expr)
            && (uses_host_surface(expr)
                || !matches!(
                    expr,
                    Expr::IntegerConstant(..) | Expr::BoolConstant(..) | Expr::Variable(..)
                ))
        {
            return emit_host_expr(out, expr, ctx);
        }
    }
    match expr {
        Expr::IntegerConstant(value, ..) => {
            if ctx.cdylib {
                out.push_str(&value.to_string());
            } else {
                out.push_str("Dynamic::from(");
                out.push_str(&value.to_string());
                out.push(')');
            }
        }
        Expr::BoolConstant(value, ..) => {
            if ctx.cdylib {
                out.push_str(if *value { "1" } else { "0" });
            } else {
                out.push_str("Dynamic::from(");
                out.push_str(if *value { "true" } else { "false" });
                out.push(')');
            }
        }
        Expr::StringConstant(value, ..) => {
            out.push_str("Dynamic::from(");
            out.push_str(&format!("{value:?}"));
            out.push(')');
        }
        Expr::Unit(..) => out.push_str(ctx.unit_expr()),
        Expr::Variable(ident, ..) => out.push_str(ident.1.as_str()),
        Expr::Dot(..) if is_args_len_expr(expr) => out.push_str("rh_args_len()"),
        Expr::Dot(..)
            if var_len_name(expr)
                .is_some_and(|name| ctx.scope.get(name).copied() == Some(ValueKind::String)) =>
        {
            out.push('(');
            out.push_str(var_len_name(expr).expect("checked string binding"));
            out.push_str(".chars().count() as INT)");
        }
        Expr::Dot(..) if is_var_len_expr(expr) => emit_host_expr(out, expr, ctx)?,
        Expr::FnCall(call, ..) => emit_call(out, call, ctx)?,
        Expr::Stmt(block) => {
            out.push_str("{ ");
            emit_block(out, block, ctx, true)?;
            out.push_str(" }");
        }
        other if ctx.cdylib && uses_host_surface(other) => emit_host_expr(out, expr, ctx)?,
        other => {
            return Err(RhError::Transpile(format!(
                "unsupported expression in rh-2: {other:?}"
            )));
        }
    }
    Ok(())
}

fn emit_std_fs_exists(out: &mut String, path: &Expr, ctx: &mut EmitCtx) -> Result<bool, RhError> {
    let mut path_expr = String::new();
    if !emit_native_string(&mut path_expr, path, ctx)? {
        return Ok(false);
    }
    out.push_str("rh_std_fs_exists(");
    out.push_str(&path_expr);
    out.push(')');
    Ok(true)
}

fn emit_std_fs_read_to_string(
    out: &mut String,
    path: &Expr,
    ctx: &mut EmitCtx,
) -> Result<bool, RhError> {
    let mut path_expr = String::new();
    if !emit_native_string(&mut path_expr, path, ctx)? {
        return Ok(false);
    }
    out.push_str("rh_std_fs_read_to_string(");
    out.push_str(&path_expr);
    out.push(')');
    Ok(true)
}

fn emit_native_string(out: &mut String, expr: &Expr, ctx: &mut EmitCtx) -> Result<bool, RhError> {
    match expr {
        Expr::StringConstant(value, ..) => out.push_str(&format!("{value:?}")),
        Expr::Variable(ident, ..)
            if ctx.scope.get(ident.1.as_str()).copied() == Some(ValueKind::String) =>
        {
            out.push('&');
            out.push_str(ident.1.as_str());
        }
        _ if args_index_expr(expr).is_some() => {
            out.push('&');
            emit_args_index(out, args_index_expr(expr).expect("checked args index"), ctx)?;
        }
        _ => return Ok(false),
    }
    Ok(true)
}

fn emit_string_contains(out: &mut String, expr: &Expr, ctx: &EmitCtx) -> bool {
    let Expr::Dot(boxed, ..) = expr else {
        return false;
    };
    let Expr::Variable(ident, ..) = &boxed.lhs else {
        return false;
    };
    if ctx.scope.get(ident.1.as_str()).copied() != Some(ValueKind::String) {
        return false;
    }
    let Expr::MethodCall(call, ..) = &boxed.rhs else {
        return false;
    };
    if call.name != "contains" || call.args.len() != 1 {
        return false;
    }
    let Expr::StringConstant(needle, ..) = &call.args[0] else {
        return false;
    };
    out.push('(');
    out.push_str(ident.1.as_str());
    out.push_str(".contains(");
    out.push_str(&format!("{needle:?}"));
    out.push_str(") as INT)");
    true
}

fn emit_args_index(out: &mut String, index: &Expr, ctx: &mut EmitCtx) -> Result<(), RhError> {
    if !is_pure_int_expr(index) {
        return Err(RhError::Transpile(
            "native args index must be a pure integer expression".into(),
        ));
    }
    out.push_str("rh_arg(");
    emit_expr(out, index, ctx)?;
    out.push(')');
    Ok(())
}

fn emit_call(out: &mut String, call: &rhai::FnCallExpr, ctx: &mut EmitCtx) -> Result<(), RhError> {
    if let Some(op) = &call.op_token {
        return emit_op(out, op, &call.args, ctx);
    }
    if call.name == "print" && !ctx.cdylib {
        out.push_str("println!(");
        for (index, arg) in call.args.iter().enumerate() {
            if index > 0 {
                out.push_str(", ");
            }
            emit_expr(out, arg, ctx)?;
        }
        out.push(')');
        return Ok(());
    }
    if call.name == "throw" && ctx.cdylib {
        if ctx.in_try() {
            return emit_throw_expr(out, call, ctx);
        }
        let mut snippet = String::from("throw ");
        snippet.push_str(&expr_to_rhai(&call.args[0])?);
        out.push_str("rh_host_eval_int(");
        out.push_str(&format!("{:?}, ", snippet));
        ctx.emit_scope_json_expr(out);
        return Ok(());
    }
    Err(RhError::Transpile(format!(
        "unsupported call `{}` in rh-2",
        call.name
    )))
}

fn emit_op(out: &mut String, op: &Token, args: &[Expr], ctx: &mut EmitCtx) -> Result<(), RhError> {
    match (op, args.len()) {
        (Token::Plus, 2) => binary(out, "+", &args[0], &args[1], ctx),
        (Token::Minus, 2) => binary(out, "-", &args[0], &args[1], ctx),
        (Token::Multiply, 2) => binary(out, "*", &args[0], &args[1], ctx),
        (Token::Divide, 2) => binary(out, "/", &args[0], &args[1], ctx),
        (Token::Modulo, 2) => binary(out, "%", &args[0], &args[1], ctx),
        (Token::Equals, 2) | (Token::EqualsTo, 2) => {
            comparison_binary(out, "==", &args[0], &args[1], ctx)
        }
        (Token::NotEqualsTo, 2) => comparison_binary(out, "!=", &args[0], &args[1], ctx),
        (Token::GreaterThan, 2) => comparison_binary(out, ">", &args[0], &args[1], ctx),
        (Token::GreaterThanEqualsTo, 2) => comparison_binary(out, ">=", &args[0], &args[1], ctx),
        (Token::LessThan, 2) => comparison_binary(out, "<", &args[0], &args[1], ctx),
        (Token::LessThanEqualsTo, 2) => comparison_binary(out, "<=", &args[0], &args[1], ctx),
        (Token::And, 2) => logical_binary(out, "&&", &args[0], &args[1], ctx),
        (Token::Or, 2) => logical_binary(out, "||", &args[0], &args[1], ctx),
        (Token::Minus, 1) => {
            out.push_str("(-(");
            emit_expr(out, &args[0], ctx)?;
            out.push_str("))");
            Ok(())
        }
        (Token::Bang, 1) => {
            out.push_str("(!(");
            emit_expr(out, &args[0], ctx)?;
            out.push_str("))");
            Ok(())
        }
        _ => Err(RhError::Transpile(format!(
            "unsupported operator `{op:?}` in rh-0"
        ))),
    }
}

fn comparison_binary(
    out: &mut String,
    op: &str,
    lhs: &Expr,
    rhs: &Expr,
    ctx: &mut EmitCtx,
) -> Result<(), RhError> {
    if ctx.cdylib {
        out.push('(');
        binary(out, op, lhs, rhs, ctx)?;
        out.push_str(") as INT");
    } else {
        binary(out, op, lhs, rhs, ctx)?;
    }
    Ok(())
}

fn logical_binary(
    out: &mut String,
    op: &str,
    lhs: &Expr,
    rhs: &Expr,
    ctx: &mut EmitCtx,
) -> Result<(), RhError> {
    if ctx.cdylib {
        out.push('(');
        emit_expr(out, lhs, ctx)?;
        out.push(' ');
        out.push_str(op);
        out.push(' ');
        emit_expr(out, rhs, ctx)?;
        out.push_str(") as INT");
    } else {
        binary(out, op, lhs, rhs, ctx)?;
    }
    Ok(())
}

fn binary(
    out: &mut String,
    op: &str,
    lhs: &Expr,
    rhs: &Expr,
    ctx: &mut EmitCtx,
) -> Result<(), RhError> {
    out.push('(');
    emit_expr(out, lhs, ctx)?;
    out.push(' ');
    out.push_str(op);
    out.push(' ');
    emit_expr(out, rhs, ctx)?;
    out.push(')');
    Ok(())
}

#[cfg(test)]
mod tests {
    use rhai::Stmt;

    use super::{CdylibExecutionMode, transpile, transpile_cdylib, transpile_cdylib_with_mode};

    #[test]
    fn transpiles_add_fn() {
        let rust = transpile("fn add(a, b) { a + b }").expect("transpile");
        assert!(rust.contains("pub fn add"));
        assert!(rust.contains("a + b"));
    }

    #[test]
    fn cdylib_transpile_uses_int_and_unsafe_export() {
        let rust = transpile_cdylib("fn entry() { 42 }").expect("transpile");
        assert!(rust.contains("fn entry() -> INT"));
        assert!(rust.contains("type INT = i64;"));
        assert!(!rust.contains("rhai::"));
        assert!(rust.contains("#[no_mangle]"));
    }

    #[test]
    fn compat_delegating_pack_uses_owned_int_abi() {
        let rust =
            transpile_cdylib("fn entry() { switch 1 { 1 => 42, _ => 0 } }").expect("transpile");
        assert!(rust.contains("compat delegating"));
        assert!(rust.contains("type INT = i64;"));
        assert!(!rust.contains("rhai::"));
    }

    #[test]
    fn cdylib_transpile_emits_while_loop() {
        let source = include_str!("../../../fixtures/rh/while.rh");
        let rust = transpile_cdylib(source).expect("transpile");
        assert!(rust.contains("while "), "expected while in:\n{rust}");
    }

    #[test]
    fn cdylib_transpile_emits_std_fs_exists_literal_fast_path() {
        let source = include_str!("../../../fixtures/rh/stdlib.rh");
        let rust = transpile_cdylib(source).expect("transpile");
        assert!(rust.contains("rh_std_fs_exists(\"/tmp\")"));
        assert!(!rust.contains("rh_host_eval_int(\"std::fs::exists"));
    }

    #[test]
    fn cdylib_transpile_emits_std_fs_exists_arg_binding_fast_path() {
        let output =
            transpile_cdylib_with_mode("fn entry() { let path = args[0]; std::fs::exists(path) }")
                .expect("transpile");
        assert_eq!(
            output.execution_mode,
            CdylibExecutionMode::Native,
            "{}",
            output.rust
        );
        assert!(output.rust.contains("rh_std_fs_exists(&path)"));
    }

    #[test]
    fn cdylib_transpile_emits_read_and_contains_fast_path() {
        let output = transpile_cdylib_with_mode(
            "fn entry() { let path = args[0]; let text = std::fs::read_to_string(path); text.contains(\"agenterm\") }",
        )
        .expect("transpile");
        assert_eq!(
            output.execution_mode,
            CdylibExecutionMode::Native,
            "{}",
            output.rust
        );
        assert!(output.rust.contains("rh_std_fs_read_to_string(&path)"));
        assert!(output.rust.contains("text.contains(\"agenterm\") as INT"));
    }

    #[test]
    fn cdylib_transpile_emits_for_int_range() {
        let source = include_str!("../../../fixtures/rh/for-range.rh");
        let rust = transpile_cdylib(source).expect("transpile");
        assert!(
            rust.contains("for value in 1..5"),
            "expected native for-range in:\n{rust}"
        );
    }

    #[test]
    fn fleet_ast_is_dot_method_chain() {
        let ast = super::parse("fn entry() { fleet.protocol.info() }").expect("parse");
        let def = ast.iter_fn_def().next().expect("fn");
        let stmt = def.body.iter().next().expect("stmt");
        let call = match stmt {
            Stmt::Expr(expr) => {
                super::super::fleet::parse_fleet_call(expr.as_ref()).expect("fleet")
            }
            other => panic!("unexpected stmt: {other:?}"),
        };
        assert_eq!(call.operation_id, "protocol.info");
    }

    #[test]
    fn cdylib_transpile_emits_for_dyn_int_range() {
        let source = include_str!("../../../fixtures/rh/for-dyn-range.rh");
        let rust = transpile_cdylib(source).expect("transpile");
        assert!(
            rust.contains("for value in 1..limit"),
            "expected native dynamic for-range in:\n{rust}"
        );
        assert!(!rust.contains("rh_host_eval_int(\"for"));
    }

    #[test]
    fn cdylib_transpile_emits_for_var_len_range() {
        let rust = transpile_cdylib(
            "fn entry() { let total = 0; for index in 1..args.len { total += index; } total }",
        )
        .expect("transpile");
        assert!(
            rust.contains("for index in 1.."),
            "expected native for-range in:\n{rust}"
        );
        assert!(
            rust.contains("rh_args_len()"),
            "expected native args length bound in:\n{rust}"
        );
        assert!(!rust.contains("rh_host_eval_int(\"for"));
    }

    #[test]
    fn int_for_plan_skips_span_check_for_dynamic_bounds() {
        let ast = super::parse("fn entry() { for i in 0..count { 0 } }").expect("parse");
        let def = ast.iter_fn_def().next().expect("fn");
        let stmt = def.body.iter().next().expect("stmt");
        let rhai::Stmt::For(boxed, ..) = stmt else {
            panic!("expected for stmt");
        };
        let (_, _, flow) = boxed.as_ref();
        let plan = super::int_for_plan(&flow.expr).expect("plan");
        assert!(matches!(
            plan,
            super::IntForPlan::Exclusive {
                start: super::IntForBound::Const(0),
                end: super::IntForBound::Expr(_),
            }
        ));
    }

    #[test]
    fn cdylib_emits_native_args_len() {
        let rust = transpile_cdylib("fn entry() { args.len() }").expect("transpile");
        let entry = rust
            .split_once("pub fn entry() -> INT {")
            .and_then(|(_, suffix)| suffix.split_once("fn rh_entry_internal()"))
            .map(|(entry, _)| entry)
            .expect("entry");
        assert!(entry.contains("rh_args_len()"), "{entry}");
        assert!(!entry.contains("rh_host_eval_int"), "{entry}");
        assert!(!entry.contains("rh_host_run_script"), "{entry}");
    }

    #[test]
    fn cdylib_emits_native_utf8_arg_and_string_len() {
        let output =
            transpile_cdylib_with_mode("fn entry() { let first = args[0]; args.len + first.len }")
                .expect("transpile");
        assert_eq!(
            output.execution_mode,
            CdylibExecutionMode::Native,
            "{}",
            output.rust
        );
        let entry = output
            .rust
            .split_once("pub fn entry() -> INT {")
            .and_then(|(_, suffix)| suffix.split_once("fn rh_entry_internal()"))
            .map(|(entry, _)| entry)
            .expect("entry");
        assert!(entry.contains("rh_arg(0)"), "{entry}");
        assert!(entry.contains("first.chars().count() as INT"), "{entry}");
        assert!(!entry.contains("rh_host_eval_int"), "{entry}");
    }

    #[test]
    fn transpiles_fleet_protocol_info_for_cdylib() {
        let rust = transpile_cdylib("fn entry() { fleet.protocol.info(); 9 }").expect("transpile");
        assert!(rust.contains("rh_fleet_call"));
        assert!(rust.contains("protocol.info"));
    }
}
