//! Q12 criterion ⑤ — is the INTERPRETATION route structurally immune to every second gate?
//!
//! Thesis (from Q9): the interpreter runs the neutral IR by WALKING it — it never allocates
//! executable memory, never writes machine code, never jumps into a data buffer, never emits
//! a relocation. If that is true, then by CONSTRUCTION it has zero surface for all of the
//! "second gate" hazards, because there is no generated code to:
//!   * land on   (CET-IBT / ENDBR64)     -- no indirect branch into generated bytes
//!   * flush     (I-cache coherence)     -- no bytes written to be executed
//!   * unwind    (RtlAddFunctionTable)   -- no synthetic frame the OS unwinder can't read
//!   * relocate  (PC32 ±2GB truncation)  -- no relocation applied at all
//!
//! This probe makes that claim EMPIRICALLY sharp using the harshest first gate from Q8:
//! it enables ACG (ProhibitDynamicCode), then:
//!   A) runs a clean-room match-based interpreter over a tiny neutral program -> correct
//!      result, having touched NO executable page; and
//!   B) attempts the Q2-style codegen path (VirtualAlloc RW -> VirtualProtect RX) -> BLOCKED
//!      with 1655, re-confirming Q8. The head-to-head shows interpretation is the one backend
//!      that needs none of the machinery the second gate guards.
//!
//! Clean-room: the interpreter below is written from scratch; no Q9 source was copied.

#![allow(non_snake_case)]
use std::ffi::c_void;

type HANDLE = *mut c_void;
type BOOL = i32;

#[link(name = "kernel32")]
extern "system" {
    fn VirtualAlloc(addr: *mut c_void, size: usize, typ: u32, protect: u32) -> *mut c_void;
    fn VirtualProtect(addr: *mut c_void, size: usize, new: u32, old: *mut u32) -> BOOL;
    fn GetLastError() -> u32;
    fn GetCurrentProcess() -> HANDLE;
    fn SetProcessMitigationPolicy(policy: i32, buf: *mut c_void, len: usize) -> BOOL;
    fn GetProcessMitigationPolicy(proc: HANDLE, policy: i32, buf: *mut c_void, len: usize) -> BOOL;
}

const MEM_COMMIT_RESERVE: u32 = 0x3000;
const PAGE_READWRITE: u32 = 0x04;
const PAGE_EXECUTE_READ: u32 = 0x20;
const PROCESS_DYNAMIC_CODE_POLICY: i32 = 2;

// --- A tiny neutral program + a code-free match interpreter (clean-room) ----------------
// Ops model the same value-word semantics Q1's IR uses (const/add/mul/xor/shl). No machine
// code, no register names — pure evaluation. This is the shape of Q9's `eval_op`.
#[allow(dead_code)]
enum Op {
    Const(u64),
    Add(usize, usize),
    Mul(usize, usize),
    Xor(usize, usize),
    Shl(usize, u32),
}

/// Evaluate a straight-line program into a value array. Zero codegen: the "execution
/// engine" is this `match`. This is the whole immunity argument in one function.
fn interp(prog: &[Op]) -> u64 {
    let mut v = vec![0u64; prog.len()];
    for (i, op) in prog.iter().enumerate() {
        v[i] = match op {
            Op::Const(x) => *x,
            Op::Add(a, b) => v[*a].wrapping_add(v[*b]),
            Op::Mul(a, b) => v[*a].wrapping_mul(v[*b]),
            Op::Xor(a, b) => v[*a] ^ v[*b],
            Op::Shl(a, s) => v[*a].wrapping_shl(*s),
        };
    }
    *v.last().unwrap()
}

fn acg_state() -> u32 {
    let mut val: u32 = 0;
    unsafe {
        GetProcessMitigationPolicy(
            GetCurrentProcess(),
            PROCESS_DYNAMIC_CODE_POLICY,
            &mut val as *mut u32 as *mut c_void,
            4,
        );
    }
    val
}

fn enable_acg() -> Result<(), u32> {
    let mut val: u32 = 1; // bit0 = ProhibitDynamicCode
    let ok = unsafe {
        SetProcessMitigationPolicy(PROCESS_DYNAMIC_CODE_POLICY, &mut val as *mut u32 as *mut c_void, 4)
    };
    if ok != 0 { Ok(()) } else { Err(unsafe { GetLastError() }) }
}

fn main() {
    println!("=== Q12 ⑤ interpretation-immunity probe (Windows / x86_64, measured) ===");

    // Enable the harshest first gate (Q8's ACG). Under it, ALL executable-memory generation
    // is forbidden — the strongest possible check that a backend generates no code.
    match enable_acg() {
        Ok(()) => println!("ACG enabled at runtime; DynamicCode policy now = {:#x}", acg_state()),
        Err(e) => println!("ACG could not be enabled (err={}); policy = {:#x}", e, acg_state()),
    }

    // A) INTERPRETER under ACG. Compute ((7*191) xor 0xABCD) << 3, code-free.
    let prog = [
        Op::Const(7),            // v0
        Op::Const(191),          // v1
        Op::Mul(0, 1),           // v2 = 1337
        Op::Const(0xABCD),       // v3
        Op::Xor(2, 3),           // v4
        Op::Shl(4, 3),           // v5 = result
    ];
    let want = (((7u64 * 191) ^ 0xABCD) << 3) as u64;
    let got = interp(&prog);
    println!(
        "  [A] interpreter under ACG: result = {} (want {}) => {}",
        got, want, if got == want { "OK, ran with ZERO executable pages" } else { "WRONG" }
    );
    println!("      it allocated no RX memory, did no indirect jump into generated bytes,");
    println!("      registered no unwind table, applied no relocation => no second-gate surface.");

    // B) CODEGEN path under ACG (the Q2/Q9-lower route) — must be blocked (Q8 re-confirm).
    unsafe {
        let mem = VirtualAlloc(std::ptr::null_mut(), 4096, MEM_COMMIT_RESERVE, PAGE_READWRITE);
        if mem.is_null() {
            println!("  [B] codegen path: VirtualAlloc(RW) NULL err={}", GetLastError());
        } else {
            let stub: [u8; 6] = [0xB8, 0x2A, 0x00, 0x00, 0x00, 0xC3];
            std::ptr::copy_nonoverlapping(stub.as_ptr(), mem as *mut u8, stub.len());
            let mut old = 0u32;
            let ok = VirtualProtect(mem, 4096, PAGE_EXECUTE_READ, &mut old);
            if ok == 0 {
                println!(
                    "  [B] codegen path under ACG: VirtualProtect(->RX) BLOCKED, err={} (1655=DYNAMIC_CODE_BLOCKED)",
                    GetLastError()
                );
                println!("      => the code-generating backend cannot even reach the SECOND gate here;");
                println!("         it dies at the first. The interpreter (A) sailed through both.");
            } else {
                println!("  [B] codegen path under ACG: unexpectedly SUCCEEDED (ACG not in force?)");
            }
        }
    }
    println!("=== done ===");
}
