//! BUILD-TIME tool (std host) — the "real compiler" side of copy-and-patch.
//! It does NOT ship and is NOT part of X. It:
//!   1. (caller compiles stencils.rs -> stencils.o with rustc -O2)
//!   2. parses the ELF object: per `.text.st_*` section it extracts the machine-code
//!      bytes (stripping the trailing `ret`) and the R_X86_64_PC32 relocation sites,
//!   3. maps each relocation's symbol name -> a HOLE KIND the runtime applier resolves,
//!   4. emits `stencils_gen.rs`: a const table (bytes + holes) = the STENCIL DATA.
//! This is exactly the CPython-style "produce jit_stencils.h at build time" step, in
//! ~180 lines, from scratch. Terminal users never run a compiler.

use std::fs;

fn rd_u16(b: &[u8], o: usize) -> u16 { u16::from_le_bytes([b[o], b[o + 1]]) }
fn rd_u32(b: &[u8], o: usize) -> u32 { u32::from_le_bytes([b[o], b[o + 1], b[o + 2], b[o + 3]]) }
fn rd_u64(b: &[u8], o: usize) -> u64 {
    let mut v = [0u8; 8];
    v.copy_from_slice(&b[o..o + 8]);
    u64::from_le_bytes(v)
}
fn cstr(b: &[u8], o: usize) -> String {
    let mut e = o;
    while b[e] != 0 { e += 1; }
    String::from_utf8_lossy(&b[o..e]).into_owned()
}

// hole kind codes shared with patch.rs
fn kind_of(sym: &str) -> u8 {
    match sym {
        "H_RD" => 0,
        "H_RS" => 1,
        "H_RB" => 2,
        "H_IMM" => 3,
        "H_OFF" => 4,
        "H_ENV" => 5,
        "H_A0" => 6,
        "H_A1" => 7,
        "H_A2" => 8,
        "H_A3" => 9,
        s if s.starts_with("H_CALL") => 5, // env slot (the called fn pointer)
        _ => panic!("unknown hole symbol {}", sym),
    }
}

struct Sec {
    name: String,
    typ: u32,
    off: usize,
    size: usize,
    link: u32,
    info: u32,
}

fn main() {
    let obj_path = std::env::args().nth(1).expect("usage: stencilize <stencils.o> <out.rs>");
    let out_path = std::env::args().nth(2).expect("usage: stencilize <stencils.o> <out.rs>");
    let b = fs::read(&obj_path).expect("read obj");

    assert_eq!(&b[0..4], b"\x7fELF", "not ELF");
    let shoff = rd_u64(&b, 0x28) as usize;
    let shentsize = rd_u16(&b, 0x3a) as usize;
    let shnum = rd_u16(&b, 0x3c) as usize;
    let shstrndx = rd_u16(&b, 0x3e) as usize;

    let mut secs: Vec<Sec> = Vec::new();
    for i in 0..shnum {
        let o = shoff + i * shentsize;
        secs.push(Sec {
            name: String::new(), // filled after we locate shstrtab
            typ: rd_u32(&b, o + 4),
            off: rd_u64(&b, o + 0x18) as usize,
            size: rd_u64(&b, o + 0x20) as usize,
            link: rd_u32(&b, o + 0x28),
            info: rd_u32(&b, o + 0x2c),
        });
        // stash sh_name in link temporarily? no — reread below with shstrtab
    }
    let shstr_off = secs[shstrndx].off;
    for (i, s) in secs.iter_mut().enumerate() {
        let o = shoff + i * shentsize;
        let nameoff = rd_u32(&b, o) as usize;
        s.name = cstr(&b, shstr_off + nameoff);
    }

    // symbol table + its string table
    let symtab = secs.iter().find(|s| s.typ == 2).expect("no symtab");
    let symstr_off = secs[symtab.link as usize].off;
    let sym_name = |idx: usize| -> String {
        let e = symtab.off + idx * 24;
        cstr(&b, symstr_off + rd_u32(&b, e) as usize)
    };

    // collect stencils: section ".text.st_NAME" + its ".rela.text.st_NAME"
    let mut out = String::new();
    out.push_str("// GENERATED by stencilize.rs from stencils.o (rustc -O2). DO NOT EDIT.\n");
    out.push_str("// This is the STENCIL DATA (criterion ②): per-op machine code + hole map.\n");
    out.push_str("#[derive(Clone, Copy)]\npub struct Hole { pub off: u16, pub kind: u8 }\n");
    out.push_str("#[derive(Clone, Copy)]\npub struct Stencil { pub code: &'static [u8], pub holes: &'static [Hole] }\n\n");

    let mut names: Vec<String> = Vec::new();
    let mut total_code = 0usize;
    let mut total_holes = 0usize;
    for s in &secs {
        if !s.name.starts_with(".text.st_") { continue; }
        let stname = s.name.trim_start_matches(".text.").to_string();
        let mut code: Vec<u8> = b[s.off..s.off + s.size].to_vec();
        // strip a single trailing ret (0xC3) so stencils fall through / concatenate.
        if code.last() == Some(&0xC3) { code.pop(); }
        // find matching rela section
        let rela = secs.iter().find(|r| r.typ == 4 && r.name == format!(".rela{}", s.name));
        let mut holes: Vec<(u16, u8)> = Vec::new();
        if let Some(rl) = rela {
            let n = rl.size / 24;
            for i in 0..n {
                let e = rl.off + i * 24;
                let r_offset = rd_u64(&b, e) as u16;
                let r_info = rd_u64(&b, e + 8);
                let r_type = (r_info & 0xffffffff) as u32;
                let r_sym = (r_info >> 32) as usize;
                assert_eq!(r_type, 2, "expected R_X86_64_PC32 in {}", s.name);
                let name = sym_name(r_sym);
                holes.push((r_offset, kind_of(&name)));
            }
        }
        holes.sort_by_key(|h| h.0);
        total_code += code.len();
        total_holes += holes.len();
        // emit
        out.push_str(&format!("pub static {}: Stencil = Stencil {{ code: &[", stname.to_uppercase()));
        for (i, byte) in code.iter().enumerate() {
            if i > 0 { out.push_str(", "); }
            out.push_str(&format!("0x{:02x}", byte));
        }
        out.push_str("], holes: &[");
        for (i, (off, kind)) in holes.iter().enumerate() {
            if i > 0 { out.push_str(", "); }
            out.push_str(&format!("Hole {{ off: {}, kind: {} }}", off, kind));
        }
        out.push_str("] };\n");
        names.push(stname.to_uppercase());
    }

    // summary comment
    out.push_str(&format!(
        "\n// STENCIL DATA SIZE: {} stencils, {} code bytes + {} holes*3B = {} B table total\n",
        names.len(), total_code, total_holes, total_code + total_holes * 3
    ));
    fs::write(&out_path, out).expect("write gen");
    eprintln!(
        "stencilize: {} stencils, code={} B, holes={} (*3B={}), table≈{} B",
        names.len(), total_code, total_holes, total_holes * 3, total_code + total_holes * 3
    );
    // also print the SUFFIX section used by pack: __UNUSED to keep info fields referenced
    let _ = (symtab.info, secs[0].info);
}
