/*
 * agenterm_probe.cpp -- real C++ consumer probe for libagenterm
 * (crates/agenterm-abi), milestone 62.
 *
 * include/agenterm.h has always carried the
 *
 *     #ifdef __cplusplus
 *     extern "C" {
 *     #endif
 *
 * guard -- but no C++ consumer has EVER been compiled against it. A guard
 * that is written is not a guard that holds: a C header can also fail to
 * compile as C++ for unrelated reasons (implicit void* -> T*, C++ keywords,
 * C-only initializer syntax). This probe exists to prove the header really
 * is consumable from C++ and that the guard really unmangles every export.
 *
 * Two jobs:
 *
 *   A. Header usability -- consume the public header from C++, running the
 *      same READ-ONLY sequence as examples/c/agenterm_probe.c: version /
 *      build id, capability negotiation, process self id, thread-local
 *      error record. Everything here is pure observation.
 *
 *   B. extern "C" guard coverage -- take the ADDRESS of EVERY export listed
 *      in crates/agenterm-abi/exports.txt (the single source of truth) into
 *      one table and iterate ALL of it. The symbol list is not hand-written
 *      here: it lives in `agenterm_export_addresses.inc`, GENERATED by
 *      tests/cpp_consumer.rs from exports.txt at test time (compiled with
 *      the scratch dir on the include path). Linking this program succeeds
 *      ONLY if all 55 names resolve unmangled -- i.e. the extern "C" guard
 *      really holds for every one of them.
 *
 *      The table is NEVER CALLED, only address-taken and walked: several of
 *      the 55 (agt_input_type_text, agt_native_window_close, agt_process_kill,
 *      agt_clipboard_set_text, agt_screenshot_*) would really type, really
 *      close a window, really kill a process, really write the clipboard.
 *      The read-only sequence in A is the only thing this program runs.
 *
 *      The whole table is iterated (not just table[0]) on purpose: a
 *      compiler that can prove only the first element is observed would be
 *      free to drop the other initializers, which would silently remove the
 *      references the linker needs to prove presence.
 *
 * Compiles warning-free under MSVC /W4 /WX (C++ via /TP, the same cl.exe as
 * the C consumers) and g++/clang++ -Wall -Wextra -Werror. Exit code 0.
 */
#include "agenterm.h"

#include <cstdint>
#include <cstdio>

/* ---- A. read-only header consumption ------------------------------------ */

static const char* cap_name(agt_capability cap) {
    switch (cap) {
    case AGT_CAP_PTY:
        return "PTY";
    case AGT_CAP_WINDOW_HOST:
        return "WINDOW_HOST";
    case AGT_CAP_SCREENSHOT:
        return "SCREENSHOT";
    case AGT_CAP_PROCESS_OBSERVE:
        return "PROCESS_OBSERVE";
    default:
        return "?";
    }
}

static int fail(const char* what, const char* why) {
    std::fprintf(stderr, "FAIL: %s: %s\n", what, why);
    return 1;
}

/* ---- B. extern "C" guard coverage --------------------------------------- */
/* Generated from exports.txt by cpp_consumer.rs: defines
 * `static void (*const export_table[])(void)` with the ADDRESS of every
 * export, never a call. */
#include "agenterm_export_addresses.inc"

static int verify_export_table(void) {
    const std::size_t n = sizeof(export_table) / sizeof(export_table[0]);
    for (std::size_t i = 0; i < n; ++i) {
        if (export_table[i] == nullptr) {
            return 1;
        }
    }
    std::printf("export_table=%zu symbols resolved (extern \"C\" guard holds)\n", n);
    return 0;
}

int main() {
    /* version & build id; %s requires a valid NUL-terminated C string */
    std::uint32_t version = agt_abi_version();
    std::printf("abi_version=0x%08x\n", static_cast<unsigned>(version));
    if (version != AGT_ABI_VERSION) {
        return fail("agt_abi_version", "expected AGT_ABI_VERSION");
    }

    const char* build_id = agt_build_id();
    std::printf("build_id=%s\n", build_id);
    if (build_id == nullptr) {
        return fail("agt_build_id", "NULL");
    }

    /* capability negotiation: the contract is "AGT_OK or AGT_UNSUPPORTED
     * only (never AGT_FAILED)". AGT_UNSUPPORTED is a legitimate result -- a
     * mechanism absent on this platform/build -- not a failure. */
    const agt_capability caps[4] = {AGT_CAP_PTY, AGT_CAP_WINDOW_HOST,
                                    AGT_CAP_SCREENSHOT, AGT_CAP_PROCESS_OBSERVE};
    for (agt_capability cap : caps) {
        agt_status st = agt_capability_query(cap);
        std::printf("capability(%s)=%d\n", cap_name(cap), static_cast<int>(st));
        if (st != AGT_OK && st != AGT_UNSUPPORTED) {
            return fail("agt_capability_query", cap_name(cap));
        }
    }

    std::uint32_t self_pid = agt_process_self();
    std::printf("self_pid=%u\n", static_cast<unsigned>(self_pid));
    if (self_pid == 0) {
        return fail("agt_process_self", "returned pid 0");
    }

    /* read the thread-local error record; with no prior failing call it is
     * the documented "no error" record (operation="none", code="ok") */
    agt_error err{};
    if (agt_last_error(&err) != AGT_OK) {
        return fail("agt_last_error", "call failed");
    }
    if (err.operation == nullptr || err.code == nullptr || err.message == nullptr) {
        return fail("agt_last_error", "NULL field");
    }
    std::printf("last_error: operation=%s code=%s message=%s\n", err.operation,
                err.code, err.message);

    if (verify_export_table() != 0) {
        return fail("export_table", "null entry");
    }
    return 0;
}
