//! Milestone 62 gate: prove a C++ consumer can compile, link AND run against
//! libagenterm — the first C++ consumer ever built against this header.
//!
//! `include/agenterm.h` carries an `extern "C"` guard, but every consumer so
//! far (`examples/c/*.c`) has been compiled with a C compiler, which ignores
//! the guard entirely. A guard that is written is not a guard that holds: the
//! header could fail as C++ for unrelated reasons (implicit `void*` -> `T*`,
//! C++ keywords, C-only initializer syntax). This test proves the guard
//! REALLY unmangles all 55 exports and that the header really is consumable
//! from C++.
//!
//! Two halves, both compiling the real `examples/cpp/agenterm_probe.cpp`:
//!
//! 1. **Static** — link against the staticlib with the C++ toolchain
//!    (`common::system_libs` supplies the Rust runtime's system libraries),
//!    run the probe with no DLL present. Run succeeding = the link is really
//!    static.
//! 2. **Dynamic** — link against the cdylib (MSVC import library / Unix
//!    `-lagenterm`), stage the library beside the probe and run it. On Linux
//!    `ensure_soname_alias` models the installed versioned soname (milestone
//!    56).
//!
//! The probe's address table is not hand-written: `cpp_consumer.rs` reads
//! `exports.txt` (the single source of truth) and GENERATES
//! `agenterm_export_addresses.inc` into a scratch dir under the system temp
//! dir (never the repo tree), then compiles the probe with that dir on the
//! include path. The probe iterates the WHOLE table (not just table[0]) so no
//! compiler can drop the other initializers and hide a mangled symbol from
//! the linker. LINKING succeeding = every one of the 55 names resolves
//! unmangled from C++ = the `extern "C"` guard holds for every export.
//!
//! SAFETY BOUNDARY: the generated include only takes function addresses —
//! it NEVER calls any export. Several of the 55 (`agt_input_type_text`,
//! `agt_native_window_close`, `agt_process_kill`, `agt_clipboard_set_text`,
//! `agt_screenshot_*`) would really type, really close, really kill, really
//! write. The probe's `main` runs only the read-only sequence
//! (`agt_abi_version` / `agt_build_id` / `agt_capability_query` /
//! `agt_process_self` / `agt_last_error`).
//!
//! The C++ toolchain is selected from the Rust target's own ABI, never from
//! what happens to sit on PATH: an MSVC target reuses the SAME cl.exe as the
//! C consumers (a `.cpp` source switches cl.exe to C++ mode by suffix -- no
//! `/TP`, which would misclassify the `.lib` link inputs, and no second MSVC
//! discovery), a GNU/macOS target uses PATH `c++`/`g++`/`clang++` (a C
//! compiler cannot consume a `.cpp`). The ONLY allowed skip is "no C++
//! compiler matching the target ABI found" (format `SKIP: <reason>`).

use agenterm::{ABI_MAJOR, ABI_MINOR};
use common::toolchain::{
    CCompiler, Cleanup, DIR_SEQ, ensure_soname_alias, find_cpp_compiler, locate_cdylib,
    locate_staticlib, profile_name, repo_root, run_or_panic, system_libs, target_env_name,
};
use std::path::{Path, PathBuf};
use std::process::{Command, Output};
use std::sync::atomic::Ordering;

mod common;

/// The expected export list, read straight from `exports.txt` — the single
/// source of truth. Never a hand-typed 55-line list: a hand-written list is
/// exactly the drift this gate exists to catch.
fn expected_exports() -> Vec<String> {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("exports.txt");
    let raw = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("exports.txt not found at {}: {e}", path.display()));
    raw.lines()
        .map(str::trim)
        .filter(|l| !l.is_empty() && !l.starts_with('#'))
        .map(str::to_owned)
        .collect()
}

/// Generate `agenterm_export_addresses.inc` into `scratch`: the ADDRESS of
/// every export from `exports.txt`, as C++ initializers, never a call. The
/// probe's B part includes this file.
fn write_export_addresses(scratch: &Path, exports: &[String]) -> PathBuf {
    let mut src = String::new();
    src.push_str("/* GENERATED by tests/cpp_consumer.rs from crates/agenterm-abi/\n");
    src.push_str("   exports.txt (the SSOT) at test time -- never hand-written.\n");
    src.push_str("   Takes the ADDRESS of every export; never calls one. */\n");
    src.push_str("static void (*const export_table[])(void) = {\n");
    for name in exports {
        src.push_str(&format!("    reinterpret_cast<void (*)()>({name}),\n"));
    }
    src.push_str("};\n");
    let inc = scratch.join("agenterm_export_addresses.inc");
    std::fs::write(&inc, src).expect("write generated export-address include");
    inc
}

/// Compile `examples/cpp/agenterm_probe.cpp` and link it against exactly ONE
/// library form: `staticlib` or `cdylib`. Warning-as-error flags match the C
/// consumers (`/W4 /WX` on MSVC with explicit `/TP`; `-Wall -Wextra -Werror`
/// on g++/clang++). CWD = scratch on MSVC keeps `.obj`/`.exe` out of the repo
/// tree. Returns the probe executable path.
fn compile_probe(
    label: &str,
    compiler: &CCompiler,
    scratch: &Path,
    include: &Path,
    cpp_file: &Path,
    staticlib: Option<&Path>,
    cdylib: Option<&Path>,
) -> PathBuf {
    assert!(
        staticlib.is_some() ^ cdylib.is_some(),
        "exactly one link form must be given"
    );
    let exe_name = if cfg!(windows) {
        "agenterm_probe.exe"
    } else {
        "agenterm_probe"
    };
    let exe = scratch.join(exe_name);

    let is_msvc = compiler
        .path
        .file_name()
        .and_then(|s| s.to_str())
        .map(|s| s.eq_ignore_ascii_case("cl.exe") || s.eq_ignore_ascii_case("cl"))
        .unwrap_or(false);

    let mut cc = Command::new(&compiler.path);
    // MSVC toolchain env (INCLUDE/LIB/PATH/...) must be applied verbatim,
    // otherwise cl fails with C1083 (cannot open include file 'stddef.h').
    for (k, v) in &compiler.env {
        cc.env(k, v);
    }
    if is_msvc {
        // /W4 /WX = warnings are errors. NO /TP: the source is a `.cpp`, so
        // cl already compiles it as C++ by suffix -- and `/TP` would be
        // harmful: it forces EVERY input to be treated as a C++ source file,
        // so the .lib link inputs (agenterm.lib / agenterm.dll.lib / the
        // system ws2_32.lib ...) would be handed to c1xx as sources instead
        // of to the linker (C2220 on the first .lib, C1083 for the rest).
        // cl re-parses the raw command line (not CommandLineToArgvW rules),
        // so each path-bearing option is a single argument. CWD = scratch
        // keeps the .obj and .exe out of the repo.
        cc.current_dir(scratch);
        cc.arg("/nologo").arg("/W4").arg("/WX");
        cc.arg(format!("/I{}", include.display()));
        // scratch carries the GENERATED agenterm_export_addresses.inc
        cc.arg(format!("/I{}", scratch.display()));
        cc.arg(cpp_file);
        cc.arg("/Foagenterm_probe.obj");
        if let Some(sl) = staticlib {
            cc.arg(sl);
            // Rust runtime system libs, resolved by file name against the LIB
            // search path from the toolchain env.
            for lib in system_libs(true) {
                cc.arg(lib);
            }
        } else if let Some(cd) = cdylib {
            let import_lib = cd.with_file_name("agenterm.dll.lib");
            assert!(
                import_lib.is_file(),
                "MSVC import library missing next to {} — build with \
                 `cargo build -p agenterm-abi --profile abi-dev`",
                cd.display()
            );
            cc.arg(&import_lib);
        }
        cc.arg(format!("/Fe{exe_name}"));
    } else {
        cc.arg("-Wall").arg("-Wextra").arg("-Werror");
        cc.arg("-I").arg(include);
        // scratch carries the GENERATED agenterm_export_addresses.inc
        cc.arg("-I").arg(scratch);
        cc.arg(cpp_file);
        if let Some(sl) = staticlib {
            cc.arg(sl);
            for lib in system_libs(false) {
                cc.arg(lib);
            }
        } else if let Some(cd) = cdylib {
            let lib_dir = cd.parent().expect("cdylib has a parent dir");
            cc.arg("-L").arg(lib_dir).arg("-lagenterm");
        }
        cc.arg("-o").arg(&exe);
    }
    run_or_panic(label, &mut cc);
    exe
}

/// Run the probe. For the dynamic form, stage the cdylib beside the probe
/// (Windows loads DLLs from the executable's own directory) and point the
/// loader at its dir on Unix; on Linux `ensure_soname_alias` models the
/// versioned soname first (milestone 56). The static form runs with NO
/// library present — that is what proves the link is really static.
fn run_probe(label: &str, scratch: &Path, exe: &Path, cdylib: Option<&Path>) -> Output {
    if let Some(cd) = cdylib {
        if cfg!(windows) {
            std::fs::copy(cd, scratch.join(cd.file_name().expect("cdylib file name")))
                .expect("copy cdylib next to the probe executable");
        }
        ensure_soname_alias(cd);
        let mut run = Command::new(exe);
        if cfg!(target_os = "macos") {
            run.env("DYLD_LIBRARY_PATH", cd.parent().unwrap());
        } else if !cfg!(windows) {
            run.env("LD_LIBRARY_PATH", cd.parent().unwrap());
        }
        run_or_panic(label, &mut run)
    } else {
        run_or_panic(label, &mut Command::new(exe))
    }
}

/// Print the probe stdout and assert the two anti-drift lines: the ABI
/// version (computed from the crate's own constants — never a hard-coded
/// literal that would go stale on the next ABI bump) and the generated
/// export-table size (must equal exports.txt's count, proving the WHOLE
/// table was walked).
fn assert_probe_stdout(out: &Output, exports_len: usize) {
    let stdout = String::from_utf8_lossy(&out.stdout);
    let stderr = String::from_utf8_lossy(&out.stderr);
    print!("{stdout}");
    eprint!("{stderr}");

    let abi_version = ((ABI_MAJOR as u32) << 16) | ABI_MINOR as u32;
    let expected_line = format!("abi_version=0x{abi_version:08x}");
    assert!(
        stdout.contains(&expected_line),
        "probe stdout must contain {expected_line}, got:\n{stdout}"
    );
    let expected_table = format!("export_table={exports_len} symbols resolved");
    assert!(
        stdout.contains(&expected_table),
        "probe stdout must contain {expected_table}, got:\n{stdout}"
    );
}

#[test]
fn cpp_consumer_dynamic_links_and_runs() {
    let Some(compiler) = find_cpp_compiler("cpp_consumer(dynamic)") else {
        eprintln!(
            "SKIP: no C++ compiler matching target_env={} was found (see the \
             target_env= decision line above) — cannot prove the extern \"C\" \
             guard from C++ on this machine",
            target_env_name()
        );
        return;
    };

    let root = repo_root();
    let include = root.join("include");
    let cpp_file = root.join("examples/cpp/agenterm_probe.cpp");
    assert!(
        cpp_file.is_file(),
        "missing {} (expected next to this test)",
        cpp_file.display()
    );

    let cdylib = locate_cdylib();
    eprintln!("cpp_consumer(dynamic): linking cdylib {}", cdylib.display());

    let exports = expected_exports();

    // Isolated scratch dir under the system temp dir — never the repo tree,
    // never in `git status`.
    let seq = DIR_SEQ.fetch_add(1, Ordering::Relaxed);
    let scratch =
        std::env::temp_dir().join(format!("agenterm-cpp-dynamic-{}-{seq}", std::process::id()));
    std::fs::create_dir_all(&scratch).expect("create scratch dir");
    let _cleanup = Cleanup(scratch.clone());

    // Generate the address-table include from exports.txt (the SSOT).
    write_export_addresses(&scratch, &exports);

    let exe = compile_probe(
        "cpp_consumer(dynamic) compile/link",
        &compiler,
        &scratch,
        &include,
        &cpp_file,
        None,
        Some(&cdylib),
    );

    eprintln!(
        "cpp_consumer(dynamic): dynamically linked probe = {} bytes (profile={})",
        std::fs::metadata(&exe).map(|m| m.len()).unwrap_or(0),
        profile_name()
    );

    let out = run_probe(
        "cpp_consumer(dynamic) probe run",
        &scratch,
        &exe,
        Some(&cdylib),
    );
    assert_probe_stdout(&out, exports.len());

    eprintln!(
        "cpp_consumer(dynamic): {}/{} exports resolved from C++ ({}, profile={})",
        exports.len(),
        exports.len(),
        cdylib.display(),
        profile_name()
    );
}

#[test]
fn cpp_consumer_static_links_and_runs() {
    let Some(compiler) = find_cpp_compiler("cpp_consumer(static)") else {
        eprintln!(
            "SKIP: no C++ compiler matching target_env={} was found (see the \
             target_env= decision line above) — cannot prove the extern \"C\" \
             guard from C++ on this machine",
            target_env_name()
        );
        return;
    };

    let root = repo_root();
    let include = root.join("include");
    let cpp_file = root.join("examples/cpp/agenterm_probe.cpp");
    assert!(
        cpp_file.is_file(),
        "missing {} (expected next to this test)",
        cpp_file.display()
    );

    let staticlib = locate_staticlib();
    eprintln!(
        "cpp_consumer(static): linking static library {}",
        staticlib.display()
    );

    let exports = expected_exports();

    // Isolated scratch dir under the system temp dir — never the repo tree,
    // never in `git status`.
    let seq = DIR_SEQ.fetch_add(1, Ordering::Relaxed);
    let scratch =
        std::env::temp_dir().join(format!("agenterm-cpp-static-{}-{seq}", std::process::id()));
    std::fs::create_dir_all(&scratch).expect("create scratch dir");
    let _cleanup = Cleanup(scratch.clone());

    // Generate the address-table include from exports.txt (the SSOT).
    write_export_addresses(&scratch, &exports);

    let exe = compile_probe(
        "cpp_consumer(static) compile/link",
        &compiler,
        &scratch,
        &include,
        &cpp_file,
        Some(&staticlib),
        None,
    );

    eprintln!(
        "cpp_consumer(static): statically linked probe = {} bytes (profile={})",
        std::fs::metadata(&exe).map(|m| m.len()).unwrap_or(0),
        profile_name()
    );

    // No DLL, no LD_LIBRARY_PATH: the probe is self-contained.
    let out = run_probe("cpp_consumer(static) probe run", &scratch, &exe, None);
    assert_probe_stdout(&out, exports.len());

    // Static-link proof: no agenterm dynamic library may exist anywhere in
    // the scratch dir (it never does — nothing copies one — and the run
    // already succeeded without one).
    for stray in ["agenterm.dll", "libagenterm.so", "libagenterm.dylib"] {
        assert!(
            !scratch.join(stray).exists(),
            "static-link gate violated: {stray} was placed next to the probe"
        );
    }

    eprintln!(
        "cpp_consumer(static): {}/{} exports resolved from C++ ({}, profile={})",
        exports.len(),
        exports.len(),
        staticlib.display(),
        profile_name()
    );
}
