@echo off
setlocal
if "%AGENTERM_BOOTSTRAP_TASK%"=="" exit /b 2
call :clock_cs AGENTERM_BOOTSTRAP_START_CS

for /f "usebackq delims=" %%I in (`git -C "%~dp0." rev-parse --show-toplevel 2^>nul`) do set "AGENTERM_BOOTSTRAP_REPO=%%I"
if "%AGENTERM_BOOTSTRAP_REPO%"=="" exit /b 2
pushd "%AGENTERM_BOOTSTRAP_REPO%"
call :clock_cs AGENTERM_BOOTSTRAP_CARGO_START_CS
cargo build --quiet --locked --bin agenterm-script
if errorlevel 1 goto :failed
call :clock_cs AGENTERM_BOOTSTRAP_CARGO_END_CS
call :elapsed_cs %AGENTERM_BOOTSTRAP_CARGO_START_CS% %AGENTERM_BOOTSTRAP_CARGO_END_CS% AGENTERM_BOOTSTRAP_CARGO_CS

set "AGENTERM_BOOTSTRAP_TARGET=target"
if defined CARGO_TARGET_DIR set "AGENTERM_BOOTSTRAP_TARGET=%CARGO_TARGET_DIR%"
set "AGENTERM_BOOTSTRAP_SOURCE=%AGENTERM_BOOTSTRAP_TARGET%\debug\agenterm-script.exe"
set "AGENTERM_BOOTSTRAP_DIR=%AGENTERM_BOOTSTRAP_TARGET%\task-bootstrap-%RANDOM%-%RANDOM%"
call :clock_cs AGENTERM_BOOTSTRAP_COPY_START_CS
mkdir "%AGENTERM_BOOTSTRAP_DIR%" >nul 2>nul
copy /y "%AGENTERM_BOOTSTRAP_SOURCE%" "%AGENTERM_BOOTSTRAP_DIR%\agenterm-script.exe" >nul
if errorlevel 1 goto :failed
call :clock_cs AGENTERM_BOOTSTRAP_COPY_END_CS
call :elapsed_cs %AGENTERM_BOOTSTRAP_COPY_START_CS% %AGENTERM_BOOTSTRAP_COPY_END_CS% AGENTERM_BOOTSTRAP_COPY_CS
set "AGENTERM_BOOTSTRAP_WORKER=%AGENTERM_BOOTSTRAP_DIR%\agenterm-script.exe"
call :clock_cs AGENTERM_BOOTSTRAP_SETUP_END_CS
call :elapsed_cs %AGENTERM_BOOTSTRAP_START_CS% %AGENTERM_BOOTSTRAP_SETUP_END_CS% AGENTERM_BOOTSTRAP_SETUP_CS
set /a AGENTERM_BOOTSTRAP_CARGO_BUILD_MS=AGENTERM_BOOTSTRAP_CARGO_CS*10
set /a AGENTERM_BOOTSTRAP_WORKER_COPY_MS=AGENTERM_BOOTSTRAP_COPY_CS*10
set /a AGENTERM_BOOTSTRAP_SETUP_MS=AGENTERM_BOOTSTRAP_SETUP_CS*10
set /a AGENTERM_BOOTSTRAP_OTHER_SETUP_MS=AGENTERM_BOOTSTRAP_SETUP_MS-AGENTERM_BOOTSTRAP_CARGO_BUILD_MS-AGENTERM_BOOTSTRAP_WORKER_COPY_MS
if %AGENTERM_BOOTSTRAP_OTHER_SETUP_MS% LSS 0 set "AGENTERM_BOOTSTRAP_OTHER_SETUP_MS=0"
set "AGENTERM_BOOTSTRAP_TIMING_SCHEMA=1"
set "AGENTERM_BOOTSTRAP_CLOCK_RESOLUTION_MS=10"
set "AGENTERM_BOOTSTRAP_LOCK_WAIT_STATE=included_not_separable"

"%AGENTERM_BOOTSTRAP_WORKER%" task run "%AGENTERM_BOOTSTRAP_TASK%" --manifest "%AGENTERM_BOOTSTRAP_REPO%\agenterm.tasks.json" -- %*
if errorlevel 1 goto :failed
del /q "%AGENTERM_BOOTSTRAP_WORKER%" >nul 2>nul
rmdir "%AGENTERM_BOOTSTRAP_DIR%" >nul 2>nul
popd
exit /b 0

:failed
set "AGENTERM_BOOTSTRAP_EXIT=%errorlevel%"
if defined AGENTERM_BOOTSTRAP_WORKER del /q "%AGENTERM_BOOTSTRAP_WORKER%" >nul 2>nul
if defined AGENTERM_BOOTSTRAP_DIR rmdir "%AGENTERM_BOOTSTRAP_DIR%" >nul 2>nul
popd
exit /b %AGENTERM_BOOTSTRAP_EXIT%

:clock_cs
for /f "tokens=1-4 delims=:.," %%a in ("%time: =0%") do set /a AGENTERM_BOOTSTRAP_CLOCK_CS=(((1%%a-100)*60+1%%b-100)*60+1%%c-100)*100+1%%d-100
set "%~1=%AGENTERM_BOOTSTRAP_CLOCK_CS%"
exit /b 0

:elapsed_cs
set /a AGENTERM_BOOTSTRAP_ELAPSED_CS=%~2-%~1
if %AGENTERM_BOOTSTRAP_ELAPSED_CS% LSS 0 set /a AGENTERM_BOOTSTRAP_ELAPSED_CS+=8640000
set "%~3=%AGENTERM_BOOTSTRAP_ELAPSED_CS%"
exit /b 0
