#!/bin/sh
# install.sh -- install libagenterm build artifacts into a standard prefix
# (milestone 61).
#
# The real install step the repo was missing: `packaging/pkgconfig/` only
# generated the .pc; nothing ever laid the built library out into an install
# tree. Milestone 56 proved the layout is non-trivial:
#
#   - the cdylib carries DT_SONAME=libagenterm.so.1 (Linux), so a consumer's
#     DT_NEEDED records the VERSIONED name and the versioned file must exist
#     on disk at runtime;
#   - `libagenterm.so` is only the link-time symlink for `-lagenterm`;
#   - cargo itself writes the bare `libagenterm.so`, so the versioned
#     filename is something an install step has to produce.
#
# This script is that step: it lays out the built artifacts under
# `<prefix>` as:
#
#   <includedir>/agenterm.h
#   <libdir>/libagenterm.a
#   <libdir>/libagenterm.so.1 + libagenterm.so -> libagenterm.so.1  (Linux)
#   <libdir>/libagenterm.dylib                                      (macOS)
#   <libdir>/pkgconfig/libagenterm.pc   (generated by generate-pc.sh, never
#                                        re-implemented here)
#
# and then self-checks the result (all files present, Linux symlink points
# at a non-empty real file). It is idempotent: installing twice into the
# same prefix overwrites in place and yields an identical tree.
#
# # Where the `.1` comes from (why it cannot drift from build.rs)
#
# The ELF soname tracks the ABI MAJOR (`abi_version!(1, 6)` in
# crates/agenterm-abi/src/lib.rs), NOT the crate version — see the long
# rationale in crates/agenterm-abi/build.rs. This script parses that major
# from the SAME source line build.rs guards on:
#
#   build.rs    asserts `src/lib.rs` contains `abi_version!(1,` and fails
#               loudly if the major ever changes (the drift guard);
#   install.sh  parses the major out of `abi_version!(<major>, ...)` and
#               never hard-codes it.
#
# So both are derived from the same single source: bumping the ABI major
# forces build.rs to be updated (or it fails to compile) AND install.sh
# picks the new value up automatically — the two cannot disagree, and there
# is no second place to forget. (build.rs also records the soname into its
# OUT_DIR/soname.txt, but an install script never runs inside a Cargo
# build, so that path is unavailable here.)
#
# # --system
#
# Mirrors generate-pc.sh's `--system auto|linux|darwin` override: `auto`
# selects on `uname -s` and explicitly REFUSES any other platform
# (including MSYS/MINGW on Windows) rather than installing half a layout;
# `linux` / `darwin` exist for tests and cross packaging. The test
# crates/agenterm-abi/tests/install_consume.rs and the CI linux/macos jobs
# are the consumers.

set -eu

SCRIPT_DIR=$(dirname "$0")
ROOT=$(cd "$SCRIPT_DIR/.." && pwd)

usage() {
    cat >&2 <<'EOF'
usage: install.sh --prefix <dir> [--libdir <dir>] [--includedir <dir>]
                  [--artifacts <dir>] [--version <ver>]
                  [--system auto|linux|darwin]

  --prefix <dir>      install prefix (required)
  --libdir <dir>      dir to install libagenterm.{a,so,dylib} and the .pc;
                      default: <prefix>/lib
  --includedir <dir>  dir to install agenterm.h; default: <prefix>/include
  --artifacts <dir>   directory containing the built libagenterm.{a,so,dylib};
                      default: <repo-root>/target/abi-release
  --version <ver>     libagenterm version written into the .pc; default read
                      from crates/agenterm-abi/Cargo.toml
  --system <os>       force the install layout: linux | darwin | auto
                      (default auto). auto selects on `uname -s` and refuses
                      any other platform (including MSYS/MINGW). --system
                      exists for tests and cross packaging.
  -h, --help          show this help and exit

Example (from the repository root):
  sh packaging/install.sh --prefix /usr/local
EOF
    exit 1
}

die() {
    echo "install.sh: $*" >&2
    exit 1
}

PREFIX=
LIBDIR=
INCLUDEDIR=
ARTIFACTS=
VERSION=
SYSTEM=auto

while [ $# -gt 0 ]; do
    case "$1" in
        --prefix)     [ $# -ge 2 ] || usage; PREFIX=$2; shift 2 ;;
        --libdir)     [ $# -ge 2 ] || usage; LIBDIR=$2; shift 2 ;;
        --includedir) [ $# -ge 2 ] || usage; INCLUDEDIR=$2; shift 2 ;;
        --artifacts)  [ $# -ge 2 ] || usage; ARTIFACTS=$2; shift 2 ;;
        --version)    [ $# -ge 2 ] || usage; VERSION=$2; shift 2 ;;
        --system)     [ $# -ge 2 ] || usage; SYSTEM=$2; shift 2 ;;
        -h|--help)    usage ;;
        *)
            echo "install.sh: unknown argument: $1" >&2
            usage
            ;;
    esac
done

[ -n "$PREFIX" ] || { echo "install.sh: --prefix is required" >&2; usage; }

# Sensible defaults: libdir/includedir derive from the prefix, the artifacts
# directory from the repo (the CI linux/macos jobs build with --profile
# abi-release, which lands in target/abi-release), the version from the
# crate manifest.
: "${LIBDIR:=$PREFIX/lib}"
: "${INCLUDEDIR:=$PREFIX/include}"
: "${ARTIFACTS:=$ROOT/target/abi-release}"
[ -n "$VERSION" ] || {
    VERSION=$(sed -n 's/^version = "\([^"]*\)".*/\1/p' "$ROOT/crates/agenterm-abi/Cargo.toml" | head -n 1 || true)
    [ -n "$VERSION" ] || die "cannot read the crate version from crates/agenterm-abi/Cargo.toml; pass --version explicitly"
}

# ---- platform selection (mirrors generate-pc.sh: never half a layout) ----
case "$SYSTEM" in
    auto)
        case "$(uname -s)" in
            Linux)  SYSTEM=linux ;;
            Darwin) SYSTEM=darwin ;;
            *)
                die "unsupported platform '$(uname -s)' -- refusing to install half a layout. This script serves Unix; use --system=linux|darwin only for tests and cross packaging."
                ;;
        esac
        ;;
    linux|darwin) : ;;
    *)
        die "unknown --system '$SYSTEM' (expected auto|linux|darwin)"
        ;;
esac

# ---- source artifacts (all must exist before anything is written) -------
[ -d "$ARTIFACTS" ] || die "artifacts directory not found: $ARTIFACTS (build with --profile abi-release first, or pass --artifacts)"
[ -f "$ARTIFACTS/libagenterm.a" ] || die "static library not found in $ARTIFACTS: expected libagenterm.a"
[ -f "$ROOT/include/agenterm.h" ] || die "header not found: $ROOT/include/agenterm.h"

case "$SYSTEM" in
    linux)
        # ABI major from the SAME src/lib.rs line build.rs guards on — see
        # the file header for why this cannot drift from the soname build.rs
        # passes to the linker.
        ABI_MAJOR=$(sed -n 's/^[[:space:]]*abi_version!(\([0-9][0-9]*\),[[:space:]].*/\1/p' "$ROOT/crates/agenterm-abi/src/lib.rs" | head -n 1 || true)
        [ -n "$ABI_MAJOR" ] || die "cannot parse the ABI major from $ROOT/crates/agenterm-abi/src/lib.rs (expected a line 'abi_version!(<major>, ...)')"
        printf '%s' "$ABI_MAJOR" | grep -q '^[0-9][0-9]*$' || die "parsed ABI major is not a number: '$ABI_MAJOR'"
        DYLIB_SRC="$ARTIFACTS/libagenterm.so"
        DYLIB_NAME="libagenterm.so.$ABI_MAJOR"
        LINK_NAME="libagenterm.so"
        ;;
    darwin)
        DYLIB_SRC="$ARTIFACTS/libagenterm.dylib"
        DYLIB_NAME="libagenterm.dylib"
        LINK_NAME=
        ;;
esac
[ -f "$DYLIB_SRC" ] || die "dynamic library not found in $ARTIFACTS: expected $DYLIB_SRC"

# ---- install (idempotent: cp/ln overwrite in place) ----------------------
mkdir -p "$LIBDIR/pkgconfig"
mkdir -p "$INCLUDEDIR"

cp "$ROOT/include/agenterm.h" "$INCLUDEDIR/agenterm.h"
cp "$ARTIFACTS/libagenterm.a" "$LIBDIR/libagenterm.a"
cp "$DYLIB_SRC" "$LIBDIR/$DYLIB_NAME"
if [ -n "$LINK_NAME" ]; then
    rm -f "$LIBDIR/$LINK_NAME"
    ln -s "$DYLIB_NAME" "$LIBDIR/$LINK_NAME"
fi

# The .pc comes from the REAL generate-pc.sh (never a second substitution
# logic here). It needs the output directory to exist, which mkdir above
# guarantees.
sh "$ROOT/packaging/pkgconfig/generate-pc.sh" \
    --prefix "$PREFIX" \
    --libdir "$LIBDIR" \
    --includedir "$INCLUDEDIR" \
    --version "$VERSION" \
    --system "$SYSTEM" \
    --output "$LIBDIR/pkgconfig/libagenterm.pc"

# ---- self-check: every promise of the layout must hold -------------------
[ -f "$INCLUDEDIR/agenterm.h" ] || die "self-check: $INCLUDEDIR/agenterm.h missing"
[ -f "$LIBDIR/libagenterm.a" ] || die "self-check: $LIBDIR/libagenterm.a missing"
[ -f "$LIBDIR/pkgconfig/libagenterm.pc" ] || die "self-check: $LIBDIR/pkgconfig/libagenterm.pc missing"
[ -s "$LIBDIR/$DYLIB_NAME" ] || die "self-check: $LIBDIR/$DYLIB_NAME is empty"
if [ -n "$LINK_NAME" ]; then
    [ -L "$LIBDIR/$LINK_NAME" ] || die "self-check: $LIBDIR/$LINK_NAME is not a symlink"
    TARGET=$(readlink "$LIBDIR/$LINK_NAME" || true)
    [ "$TARGET" = "$DYLIB_NAME" ] || die "self-check: $LIBDIR/$LINK_NAME -> $TARGET, expected $DYLIB_NAME"
    [ -s "$LIBDIR/$TARGET" ] || die "self-check: $LIBDIR/$LINK_NAME points at empty $LIBDIR/$TARGET"
fi

echo "install.sh: installed libagenterm $VERSION ($SYSTEM layout) into $PREFIX"
echo "install.sh:   include: $INCLUDEDIR/agenterm.h"
echo "install.sh:   lib:     $LIBDIR/libagenterm.a"
echo "install.sh:   lib:     $LIBDIR/$DYLIB_NAME"
[ -n "$LINK_NAME" ] && echo "install.sh:   lib:     $LIBDIR/$LINK_NAME -> $DYLIB_NAME"
echo "install.sh:   pc:      $LIBDIR/pkgconfig/libagenterm.pc"
